namespace CardGame.Core;

/// <summary>
/// Player-facing and AI-facing metadata for a card kind that the current rules
/// engine already understands. New trick/equipment kinds must not be added here
/// until the corresponding typed resolution entry points exist.
/// </summary>
public sealed record CardDefinition(
    CardKind Kind,
    string DisplayName,
    string CategoryName,
    string Description,
    int AiPlayValue,
    int AiResponseValue,
    int HandKeepValue);

public static class CardCatalog
{
    private static readonly IReadOnlyDictionary<CardKind, CardDefinition> Definitions =
        new Dictionary<CardKind, CardDefinition>
        {
            [CardKind.GeneralWeapon] = new(CardKind.GeneralWeapon, "武将武器", "装备牌", "无花色点数，离开装备区销毁。", 40, 0, 40),
            [CardKind.RedBloodBlade] = new(CardKind.RedBloodBlade, "赤血刃", "装备牌",
                "攻击范围3（若你未拥有神御，改为0）。每回合首次你的杀对攻击范围内最远角色造成伤害时，此伤害+1。首次替换其他武器牌后，获得其技能。", 45, 0, 50),
            [CardKind.Slash] = new(
                CardKind.Slash,
                "杀",
                "基本牌",
                "选择一名角色；其未打出闪则受到 1 点伤害。",
                AiPlayValue: 0,
                AiResponseValue: 0,
                HandKeepValue: 40),
            [CardKind.FireSlash] = new(
                CardKind.FireSlash,
                "火杀",
                "基本牌",
                "选择一名角色；其未打出闪则受到 1 点火焰伤害。",
                AiPlayValue: 0,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.ThunderSlash] = new(
                CardKind.ThunderSlash,
                "雷杀",
                "基本牌",
                "选择一名角色；其未打出闪则受到 1 点雷电伤害。",
                AiPlayValue: 0,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.Alcohol] = new(
                CardKind.Alcohol,
                "酒",
                "基本牌",
                "出牌阶段使用使本回合下一张杀伤害 +1；濒死时可救援一名角色回复 1 点体力。",
                AiPlayValue: 18,
                AiResponseValue: 0,
                HandKeepValue: 35),
            [CardKind.Dodge] = new(
                CardKind.Dodge,
                "闪",
                "基本牌",
                "受到杀、火杀或雷杀时打出，抵消这次伤害。",
                AiPlayValue: 0,
                AiResponseValue: 65,
                HandKeepValue: 70),
            [CardKind.Peach] = new(
                CardKind.Peach,
                "桃",
                "基本牌",
                "出牌阶段回复自己 1 点体力；濒死时可救援一名角色。",
                AiPlayValue: 38,
                AiResponseValue: 0,
                HandKeepValue: 50),
            [CardKind.Duel] = new(
                CardKind.Duel,
                "决斗",
                "锦囊牌",
                "选择一名角色；双方交替打出杀，未打出者受到 1 点伤害。",
                AiPlayValue: 28,
                AiResponseValue: 0,
                HandKeepValue: 45),
            [CardKind.DrawTwo] = new(
                CardKind.DrawTwo,
                "无中生有",
                "锦囊牌",
                "出牌阶段使用，摸两张牌。",
                AiPlayValue: 32,
                AiResponseValue: 0,
                HandKeepValue: 38),
            [CardKind.BarbarianAssault] = new(
                CardKind.BarbarianAssault,
                "南蛮入侵",
                "锦囊牌",
                "所有其他角色依次打出杀，否则受到 1 点伤害。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.ArrowBarrage] = new(
                CardKind.ArrowBarrage,
                "万箭齐发",
                "锦囊牌",
                "所有其他角色依次打出闪，否则受到 1 点伤害。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.PeachGarden] = new(
                CardKind.PeachGarden,
                "桃园结义",
                "锦囊牌",
                "所有存活角色各回复 1 点体力。",
                AiPlayValue: 30,
                AiResponseValue: 0,
                HandKeepValue: 40),
            [CardKind.FiveGrains] = new(
                CardKind.FiveGrains,
                "五谷丰登",
                "锦囊牌",
                "公开展示牌堆顶牌；所有存活角色按座次各选择一张，余牌弃置。",
                AiPlayValue: 36,
                AiResponseValue: 0,
                HandKeepValue: 46),
            [CardKind.Dismantlement] = new(
                CardKind.Dismantlement,
                "过河拆桥",
                "锦囊牌",
                "选择一名其他角色；盲弃置其一张手牌，或弃置其一张公开装备/判定区牌。",
                AiPlayValue: 26,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.Snatch] = new(
                CardKind.Snatch,
                "顺手牵羊",
                "锦囊牌",
                "选择一名距离为 1 的其他角色；盲取其一张手牌，或获得其一张公开装备/判定区牌。",
                AiPlayValue: 30,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.UnexpectedAssault] = new(
                CardKind.UnexpectedAssault,
                "出其不意",
                "锦囊牌",
                "选择一名有手牌的其他角色；你展示其一张手牌，若出其不意有花色且与此牌花色不同，对其造成1点普通伤害。",
                AiPlayValue: 34,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.FireAttack] = new(
                CardKind.FireAttack,
                "火攻",
                "锦囊牌",
                "选择一名有手牌的角色；其展示一张手牌，你弃置一张相同花色的手牌后对其造成 1 点火焰伤害。",
                AiPlayValue: 34,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.BorrowedSword] = new(
                CardKind.BorrowedSword,
                "借刀杀人",
                "锦囊牌",
                "选择一名装备武器的其他角色及其攻击范围内的另一名角色；前者需对后者使用一张杀，否则将武器交给你。",
                AiPlayValue: 32,
                AiResponseValue: 0,
                HandKeepValue: 45),
            [CardKind.Crossbow] = new(
                CardKind.Crossbow,
                "诸葛连弩",
                "装备牌",
                "装备至武器槽；攻击范围 1，出牌阶段可使用任意数量的杀。",
                AiPlayValue: 30,
                AiResponseValue: 0,
                HandKeepValue: 36),
            [CardKind.BaguaFormation] = new(
                CardKind.BaguaFormation,
                "八卦阵",
                "装备牌",
                "装备至防具槽；每当需要使用或打出闪时，可进行一次判定，红色判定牌视为打出闪。",
                AiPlayValue: 16,
                AiResponseValue: 0,
                HandKeepValue: 32),
            [CardKind.RenwangShield] = new(
                CardKind.RenwangShield,
                "仁王盾",
                "装备牌",
                "装备至防具槽；黑色杀对你无效。",
                AiPlayValue: 22,
                AiResponseValue: 0,
                HandKeepValue: 36),
            [CardKind.OffensiveHorse] = new(
                CardKind.OffensiveHorse,
                "赤兔",
                "装备牌",
                "装备至进攻坐骑槽；你到其他角色的战斗距离 -1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.DefensiveHorse] = new(
                CardKind.DefensiveHorse,
                "绝影",
                "装备牌",
                "装备至防御坐骑槽；其他角色到你的战斗距离 +1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.Dawan] = new(
                CardKind.Dawan,
                "大宛",
                "装备牌",
                "装备至进攻坐骑槽；你到其他角色的战斗距离 -1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.Zixing] = new(
                CardKind.Zixing,
                "紫骍",
                "装备牌",
                "装备至进攻坐骑槽；你到其他角色的战斗距离 -1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.Dilu] = new(
                CardKind.Dilu,
                "的卢",
                "装备牌",
                "装备至防御坐骑槽；其他角色到你的战斗距离 +1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.Zhaohuangfeidian] = new(
                CardKind.Zhaohuangfeidian,
                "爪黄飞电",
                "装备牌",
                "装备至防御坐骑槽；其他角色到你的战斗距离 +1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.Hualiu] = new(
                CardKind.Hualiu,
                "骅骝",
                "装备牌",
                "装备至防御坐骑槽；其他角色到你的战斗距离 +1。",
                AiPlayValue: 24,
                AiResponseValue: 0,
                HandKeepValue: 34),
            [CardKind.JadeSeal] = new(
                CardKind.JadeSeal,
                "玉玺",
                "装备牌",
                "装备至宝物槽；摸牌阶段额外摸一张牌。",
                AiPlayValue: 26,
                AiResponseValue: 0,
                HandKeepValue: 38),
            [CardKind.QinggangSword] = new(
                CardKind.QinggangSword,
                "青釭剑",
                "装备牌",
                "装备至武器槽；攻击范围 2，你使用杀指定目标后无视其防具。",
                AiPlayValue: 32,
                AiResponseValue: 0,
                HandKeepValue: 38),
            [CardKind.StoneAxe] = new(
                CardKind.StoneAxe,
                "贯石斧",
                "装备牌",
                "装备至武器槽；攻击范围 3，当你的杀被闪抵消后，你可以弃置两张牌，令此杀仍造成伤害。",
                AiPlayValue: 36,
                AiResponseValue: 0,
                HandKeepValue: 40),
            [CardKind.ZhangbaSerpentSpear] = new(
                CardKind.ZhangbaSerpentSpear,
                "丈八蛇矛",
                "装备牌",
                "装备至武器槽；攻击范围 3，你可以将两张手牌当一张杀使用或打出。",
                AiPlayValue: 38,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.CixiongDoubleSwords] = new(
                CardKind.CixiongDoubleSwords,
                "雌雄双股剑",
                "装备牌",
                "装备至武器槽；攻击范围 2，使用杀指定异性目标后，可令其弃一张手牌或令你摸一张牌。",
                AiPlayValue: 37,
                AiResponseValue: 0,
                HandKeepValue: 41),
            [CardKind.QinglongCrescentBlade] = new(
                CardKind.QinglongCrescentBlade,
                "青龙偃月刀",
                "装备牌",
                "装备至武器槽；攻击范围 3，当你使用的杀被闪抵消后，你可以对同一目标再使用一张杀（无距离限制）。",
                AiPlayValue: 39,
                AiResponseValue: 0,
                HandKeepValue: 43),
            [CardKind.IceSword] = new(
                CardKind.IceSword,
                "寒冰剑",
                "装备牌",
                "装备至武器槽；攻击范围 2，当你使用杀即将造成伤害且目标有手牌或装备时，可防止此伤害并依次弃置其至多两张牌。",
                AiPlayValue: 38,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.QilinBow] = new(
                CardKind.QilinBow,
                "麒麟弓",
                "装备牌",
                "装备至武器槽；攻击范围 5，当你使用杀对目标角色造成伤害时，可弃置其装备区的一张坐骑牌。",
                AiPlayValue: 40,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.FangtianHalberd] = new(
                CardKind.FangtianHalberd,
                "方天画戟",
                "装备牌",
                "装备至武器槽；攻击范围 4，当你使用最后的手牌杀时，可额外指定至多两个合法目标。",
                AiPlayValue: 42,
                AiResponseValue: 0,
                HandKeepValue: 45),
            [CardKind.GudingBlade] = new(
                CardKind.GudingBlade,
                "古锭刀",
                "装备牌",
                "装备至武器槽；攻击范围 2，锁定技，当你使用杀对没有手牌的目标造成伤害时，此伤害 +1。",
                AiPlayValue: 39,
                AiResponseValue: 0,
                HandKeepValue: 43),
            [CardKind.ZhuqueFan] = new(
                CardKind.ZhuqueFan,
                "朱雀羽扇",
                "装备牌",
                "装备至武器槽；攻击范围 4，你可以将使用的普通杀改为火杀。",
                AiPlayValue: 41,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.GhostDragonCrescentBlade] = new(
                CardKind.GhostDragonCrescentBlade, "鬼龙斩月刀", "装备牌",
                "攻击范围 3，你使用的红色杀不能被闪响应。",
                AiPlayValue: 40, AiResponseValue: 0, HandKeepValue: 43),
            [CardKind.ScarletBloodSword] = new(
                CardKind.ScarletBloodSword, "赤血青锋", "装备牌",
                "攻击范围 2，你的杀无视防具，目标不能使用或打出手牌响应。",
                AiPlayValue: 41, AiResponseValue: 0, HandKeepValue: 44),
            [CardKind.XingtianAxe] = new(
                CardKind.XingtianAxe, "刑天破军斧", "装备牌",
                "攻击范围 4，单一目标用牌后可弃两张牌，令其本回合不能使用或打出手牌且防具失效。",
                AiPlayValue: 42, AiResponseValue: 0, HandKeepValue: 45),
            [CardKind.Tengjia] = new(
                CardKind.Tengjia,
                "藤甲",
                "装备牌",
                "锁定技，南蛮入侵、万箭齐发和普通杀对你无效；你受到的火焰伤害 +1。",
                AiPlayValue: 36,
                AiResponseValue: 0,
                HandKeepValue: 40),
            [CardKind.SilverLion] = new(
                CardKind.SilverLion,
                "白银狮子",
                "装备牌",
                "锁定技，你受到大于1点的伤害时将伤害值改为1；失去装备区里的白银狮子后回复1点体力。",
                AiPlayValue: 39,
                AiResponseValue: 0,
                HandKeepValue: 42),
            [CardKind.WoodenOx] = new(
                CardKind.WoodenOx,
                "木牛流马",
                "装备牌",
                "出牌阶段限一次，将一张手牌置于木牛流马下，并可将木牛流马移动给其他角色；其持有者可使用或打出其中的牌。",
                AiPlayValue: 37,
                AiResponseValue: 0,
                HandKeepValue: 41),
            [CardKind.Nullification] = new(
                CardKind.Nullification,
                "无懈可击",
                "锦囊牌",
                "抵消一张锦囊牌的效果；无懈之间可以继续互相抵消。",
                AiPlayValue: 0,
                AiResponseValue: 72,
                HandKeepValue: 52),
            [CardKind.IronChain] = new(
                CardKind.IronChain,
                "铁索连环",
                "锦囊牌",
                "横置或重置一至两名其他存活角色；被火焰或雷电伤害时，连环角色会传导同量伤害。",
                AiPlayValue: 25,
                AiResponseValue: 0,
                HandKeepValue: 48),
            [CardKind.Indulgence] = new(
                CardKind.Indulgence,
                "乐不思蜀",
                "锦囊牌",
                "选择一名其他角色；其下个回合判定，若结果不为红桃则跳过出牌阶段。",
                AiPlayValue: 34,
                AiResponseValue: 0,
                HandKeepValue: 46),
            [CardKind.SupplyShortage] = new(
                CardKind.SupplyShortage,
                "兵粮寸断",
                "锦囊牌",
                "选择一名有手牌的其他角色；其下个回合判定，若结果不为梅花则跳过摸牌阶段。",
                AiPlayValue: 32,
                AiResponseValue: 0,
                HandKeepValue: 44),
            [CardKind.Lightning] = new(
                CardKind.Lightning,
                "闪电",
                "锦囊牌",
                "置于自己的判定区；下个回合判定为黑桃 2 至 9 时受到 3 点雷电伤害，否则移至下一名存活角色的判定区。",
                AiPlayValue: 20,
                AiResponseValue: 0,
                HandKeepValue: 48)
        };

    public static IReadOnlyList<CardDefinition> ImplementedCards { get; } =
        Definitions.Values.OrderBy(definition => definition.Kind).ToArray();

    public static CardDefinition Get(CardKind kind) =>
        Definitions.TryGetValue(kind, out var definition)
            ? definition
            : throw new ArgumentOutOfRangeException(nameof(kind), kind, "No card content is registered for this kind.");
}
