using System.Reflection;
using System.Text.Json;
using CardGame.Core;
using CardGame.Content.Standard;
using static BoundaryLiDianChecks;
internal static class BoundaryHuaXiongChecks
{
    const string Skill="boundary:shizhan-current",Binding="selected-actor-duel",Yao="boundary:yaowu-current";
    static int FailSequence;
    public static void DefinitionsAndColors()
    {
        foreach(var black in new[]{false,true})
        {
            var(g,r)=Start(kind:"slash",black:black);var h0=g.State.Players[0].HandCount;var h1=g.State.Players[1].HandCount;
            var a=g.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Slash&&a.TargetSeat==1);
            Accept(g,new PlayCardCommand(0,a.CardId!.Value,[1],g.Revision,P(g)!.PromptId));Settle(g);
            Require(g.Events.Select(e=>e.Payload).OfType<ProgramBindingStartedEvent>().Any(e=>e.SkillId==Yao),"Real physical Slash damage reaches current Yaowu.");
            Require(g.State.Players[0].HandCount==h0-1+(black?0:1)&&g.State.Players[1].HandCount==h1+(black?1:0),"Actual physical red/non-red damage Draw recipient.");Cold(g,r);Evidence(g,"physical-"+black);
        }
        var(effective,er)=Start(kind:"slash",black:true,hongyan:true);var effectiveHand=effective.State.Players[0].HandCount;var sa=effective.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Slash&&a.TargetSeat==1);Accept(effective,new PlayCardCommand(0,sa.CardId!.Value,[1],effective.Revision,P(effective)!.PromptId));Settle(effective);Require(effective.State.Players[0].HandCount==effectiveHand,"Frozen Hongyan effective red appearance on printed Spade Slash gives source Draw1.");Cold(effective,er);Evidence(effective,"hongyan-effective-red");
        foreach(var black in new[]{false,true})
        {
            var(l,lr)=Start(kind:"lightning",black:black);var a=l.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Lightning&&a.TargetSeat==0);Accept(l,new PlayCardCommand(0,a.CardId!.Value,[0],l.Revision,P(l)!.PromptId));Settle(l);var beforeHp=l.State.Players[0].Hp;var beforeHand=l.State.Players[0].HandCount;Accept(l,new EndPlayPhaseCommand(0,l.Revision,P(l)!.PromptId));Reach(l,p=>p.Kind==DecisionKind.PlayCard&&p.PlayerSeat==0);Require(l.Events.Select(e=>e.Payload).OfType<JudgmentResolvedEvent>().Any(e=>e.Reason=="trick.lightning"&&e.Succeeded)&&l.State.Players[0].Hp==beforeHp-3,"Actual physical Lightning makes source-less damage through real judgment.");Evidence(l,"lightning-observed-"+black);Require(l.State.Players[0].HandCount==beforeHand+(black?1:0),"Source-less red Lightning cannot Draw for placeholder source; non-red physical Lightning Draws once per damage, not three points.");Cold(l,lr);Evidence(l,"source-less-lightning-"+black);
        }
        var(z,zr)=Start(kind:"lightning",black:true,gain:true,hp:2);var za=z.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Lightning&&a.TargetSeat==0);Accept(z,new PlayCardCommand(0,za.CardId!.Value,[0],z.Revision,P(z)!.PromptId));Settle(z);var zh=z.State.Players[0].HandCount;Accept(z,new EndPlayPhaseCommand(0,z.Revision,P(z)!.PromptId));Reach(z,p=>p.SkillPrompt?.SkillId=="fixture:hx-gain");var zp=z.ResolutionStack.OfType<ProgramSkillFrame>().Single(f=>f.SkillId==Yao).DamageAppearanceReceipt!;Require(z.State.Players[0] is {Hp:0,IsAlive:true}&&zp is {HasCard:true,IsRed:false,SourceSeat:null,RecipientSeat:0,DrawIssued:true}&&z.State.Players[0].HandCount==zh+1,"Source-less non-red Lightning actually Draws once at HP0 before Dying.");Cold(z,zr);Evidence(z,"source-less-hp0-before-dying");Skip(z);Settle(z);Require(!z.State.Players[0].IsAlive,"Source-less damage resumes actual death after Yaowu gain child.");Cold(z,zr);
        var(c,cr)=Start();var hand=c.State.Players[0].HandCount;Driver(c,"cardless",[1]);Settle(c);Require(c.State.Players[0].HandCount==hand,"True cardless damage has no Yaowu benefit.");Cold(c,cr);
        var(d,dr)=Start();var before=d.State.Players[0].HandCount;Driver(d,"legacy-duel",[1,0]);Settle(d);Require(d.State.Players[0].HandCount==before+1&&!d.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Any(e=>e.CardKind==CardKind.Duel),"Legacy direct virtual Duel has explicit card kind and non-red benefit, retaining no CardUse lifecycle.");Cold(d,dr);Evidence(d,"legacy-direct-duel");
        var exact="{\"id\":\"duel\",\"minCards\":0,\"maxCards\":0,\"minTargets\":1,\"maxTargets\":1,\"targetKind\":\"otherLiving\",\"usesPerTurn\":null,\"usesPerPhase\":2,\"effects\":[{\"op\":\"useSelectedActorDuel\",\"target\":\"owner\"}]}";
        foreach(var bad in new[]{exact.Replace("\"maxCards\":0","\"maxCards\":1"),exact.Replace("otherLiving","anyLiving"),exact.Replace("\"usesPerPhase\":2","\"usesPerPhase\":1"),exact.Replace("\"maxTargets\":1","\"maxTargets\":2")})Reject("\"activations\":["+bad+"]");
        foreach(var bad in new[]{"afterDamageApplied","beforeDamageApplied"})Reject("\"triggers\":[{\"id\":\"bad\",\"window\":\""+bad+"\",\"subject\":\"damageTarget\",\"optional\":false,\"effects\":[{\"op\":\"drawByDamageCardColor\",\"target\":\"owner\"}]}]");
    }
    public static void ActualDuelAndNullification()
    {
        var(g,r)=Start(completed:true);var hp=g.State.Players[0].Hp;var hand=g.State.Players[0].HandCount;Use(g,1);Cold(g,r);Evidence(g,"duel-issued");Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:hx-completed");Cold(g,r);Evidence(g,"completed-damage-child");Activate(g);Settle(g);
        var declared=g.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Single(e=>e.CardKind==CardKind.Duel);
        Require(declared.SourceSeat==1&&declared.CardId==0&&g.State.Players[0].Hp==hp-1&&g.State.Players[0].HandCount==hand+2,"Other selected actor really Uses zero-entity Duel and owner takes non-red damage/Draw.");
        Require(g.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Count(e=>e.CardKind==CardKind.Duel)==1&&!g.ResolutionStack.OfType<ProgramSkillFrame>().Any(),"Actual Duel completion returns to its Program once.");Cold(g,r);Evidence(g,"duel-finished");
        var(n,nr)=Start(kind:"nullification",jizhi:true,completed:true);Use(n,1);Reach(n,p=>p.Kind==DecisionKind.Nullification&&p.PlayerSeat==0);Cold(n,nr);Evidence(n,"nullification");var physical=P(n)!.Choices.First(c=>c.Cards.Count==1).Cards.Single();Answer(n,c=>c.Cards.SequenceEqual([physical]));while(P(n) is {Kind:DecisionKind.Nullification,PlayerSeat:0})Answer(n,c=>c.Cards.Count==0);Reach(n,p=>p.SkillPrompt?.SkillId=="fixture:hx-completed");Cold(n,nr);Evidence(n,"completed-nullified-child");Skip(n);Settle(n);Require(n.Events.Select(e=>e.Payload).OfType<ProgramBindingStartedEvent>().Any(e=>e.SkillId=="classic:jizhi"),"Actual zero-entity Duel reaches native classic Jizhi actor trigger.");
        Require(!n.Events.Select(e=>e.Payload).OfType<DamageAppliedEvent>().Any()&&n.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Any(e=>e.CardKind==CardKind.Duel),"Real Nullification prevents the forced Duel then typed parent completes.");
        Require(n.CardMovements.Count(m=>m.CardId==physical&&m.From==CardLocation.Hand(0)&&m.To==CardLocation.Processing)==1,"Actual Nullification entity pays once.");Cold(n,nr);Evidence(n,"nullified-finished");
    }
    public static void ResponsesAndLegality()
    {
        var(g,r)=Start(kind:"slash");var h=g.State.Players[0].HandCount;Use(g,1);Reach(g,p=>p.Kind==DecisionKind.RespondSlash&&p.PlayerSeat==0);Cold(g,r);var card=P(g)!.Choices.First(c=>c.Cards.Count==1).Cards.Single();Answer(g,c=>c.Cards.SequenceEqual([card]));Settle(g);
        Require(g.Events.Select(e=>e.Payload).OfType<DamageAppliedEvent>().Single().TargetSeat==1,"Target answers a real Duel Slash then selected actor loses the Duel.");Require(g.State.Players[0].HandCount==h-1,"Red response cards do not change zero-entity Duel's non-red appearance.");Cold(g,r);Evidence(g,"duel-slash-response");
        var(k,kr)=Start(kongcheng:true);Driver(k,"empty");Settle(k);Require(!k.GetHumanLegalActions().Any(a=>a.ProgramSkillId==Skill),"Kongcheng owner cannot be a Duel target; infeasible actors disappear before quota.");Cold(k,kr);
        var(b,br)=Start(actorBan:true);Require(!Actions(b).Single().SelectableTargetSeats.Contains(1),"Selected actor Use prohibition is reflected in the candidate list.");var cp=GameCheckpointJson.Serialize(b.CreateCheckpoint());var denied=b.Submit(new UseProgramSkillCommand(0,Skill,Binding,[],[1],b.Revision,P(b)!.PromptId));Require(!denied.Accepted&&cp==GameCheckpointJson.Serialize(b.CreateCheckpoint()),"Nonoffered actor rejects without advancing or quota.");Cold(b,br);
    }
    public static void GainDyingAndPhase()
    {
        foreach(var activate in new[]{false,true})
        {
            var(g,r)=Start(gain:true,hp:1);Use(g,1);Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:hx-gain");Cold(g,r);Evidence(g,"gain-"+activate);var receipt=g.ResolutionStack.OfType<ProgramSkillFrame>().Single(f=>f.SkillId==Yao).DamageAppearanceReceipt!;
            Require(receipt is{HasCard:true,IsRed:false,RecipientSeat:0,DrawIssued:true}&&g.State.Players[0].Hp==0&&!g.ResolutionStack.OfType<DyingFrame>().Any(),"Yaowu receipt and actual Draw precede Dying even at HP zero.");if(activate){Activate(g);Cold(g,r);Evidence(g,"gain-selection");Answer(g,c=>c.Cards.Count==1);}else Skip(g);
            for(var i=0;i<70&&g.State.Players[0].IsAlive;i++){if(P(g) is{Kind:DecisionKind.RescueDying})Answer(g,c=>c.Cards.Count==0);else Accept(g,new AdvanceOneStepCommand(g.Revision));}
            Require(!g.State.Players[0].IsAlive,"After gain child completion the real recipient reaches death.");Cold(g,r);Evidence(g,"death-"+activate);
        }
        foreach(var hpActivate in new[]{false,true})
        {
            var(g,r)=Start(kind:"peach",gain:true,gainDying:true,hp:1);var original=g.State.Players[0].Hand.Select(c=>c.Id).ToArray();Use(g,1);Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:hx-gain");Activate(g);Cold(g,r);Evidence(g,"gain-dying-selection-"+hpActivate);Answer(g,c=>c.Cards.Count==1);Reach(g,p=>p.Kind==DecisionKind.RescueDying&&p.PlayerSeat==0);Cold(g,r);Evidence(g,"child-dying-"+hpActivate);
            var peach=P(g)!.Choices.First(c=>c.Cards.Count==1&&original.Contains(c.Cards[0])).Cards.Single();Answer(g,c=>c.Cards.SequenceEqual([peach]));Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:hx-hp");Cold(g,r);Evidence(g,"peach-hp-observer-"+hpActivate);if(hpActivate)Activate(g);else Skip(g);Settle(g);Require(g.State.Players[0].IsAlive&&g.State.Players[0].Hp>=1,"Real gain-child LoseHp Dying is saved by entity Peaches before original damage continuation.");Require(g.CardMovements.Count(m=>m.CardId==peach&&m.From==CardLocation.Hand(0)&&m.To==CardLocation.Processing)==1,"Rescue physical Peach pays once.");Cold(g,r);Evidence(g,"child-saved-"+hpActivate);
        }
        var(p,pr)=Start(extra:true);Use(p,1);Settle(p);Use(p,1);Settle(p);Require(!Actions(p).Any(),"Two real Uses exhaust the actual Play phase quota.");Accept(p,new EndPlayPhaseCommand(0,p.Revision,P(p)!.PromptId));Settle(p);Require(Actions(p).Any(),"An actual later Play phase receives a fresh two-use quota.");Cold(p,pr);Evidence(p,"extra-play");
    }
    public static void NativeAndOwnership()
    {
        var(ai,ar)=Start();var hint=Actions(ai).Single().ProgramAiHint!;Require(hint.TargetHpLoss==0&&hint.OwnerHpLoss==0&&hint.OwnerDraw==0&&hint.TargetValueAdjustment<0&&hint.ValueAdjustment<0,"Duel public risk prices target harm and owner risk without fixed damage or guaranteed Draw.");
        var brain=new SimpleAiBrain(0,7);var view=ai.CreateSnapshot(0);var friend=view.Players[1] with {IsRoleRevealed=true,Role=Role.Loyalist};var foe=view.Players[2] with {IsRoleRevealed=true,Role=Role.Rebel};view=view with {Players=Array.AsReadOnly(new[]{view.Players[0],friend,foe,view.Players[3]})};
        var score=typeof(SimpleAiBrain).GetMethod("ScoreProgramTarget",BindingFlags.Instance|BindingFlags.NonPublic,null,[typeof(GameSnapshot),typeof(int),typeof(SkillProgramAiHint)],null)!;
        var fs=(double)score.Invoke(brain,[view,1,hint])!;var es=(double)score.Invoke(brain,[view,2,hint])!;Require(es>fs&&es>0&&fs<0,"Public known enemy receives positive harm score, friend negative; no enemy identities are read.");Cold(ai,ar);
        var(g,r)=Start(native:true);for(var i=0;i<100&&!g.Events.Select(e=>e.Payload).OfType<ProgramSkillStartedEvent>().Any(e=>e.SkillId==Skill);i++)Accept(g,new AdvanceOneStepCommand(g.Revision));
        var started=g.Events.Select(e=>e.Payload).OfType<ProgramSkillStartedEvent>().First(e=>e.SkillId==Skill);for(var i=0;i<100&&g.ResolutionStack.OfType<ProgramSkillFrame>().Any(f=>f.SkillId==Skill);i++){if(P(g) is{Kind:DecisionKind.RespondSlash,PlayerSeat:3})Answer(g,c=>c.Cards.Count==0);else Accept(g,new AdvanceOneStepCommand(g.Revision));}
        Require(!g.ResolutionStack.OfType<ProgramSkillFrame>().Any(f=>f.SkillId==Skill)&&g.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Any(e=>e.CardKind==CardKind.Duel),"Ordinary optional native activation uses the real Duel and finishes finitely.");Console.WriteLine("Native Shizhan accepted owner="+started.OwnerSeat+" revision="+g.Revision);Cold(g,r);Evidence(g,"native");
        var(h,hr)=Start();Use(h,1);var use=h.ResolutionStack.OfType<CardUseFrame>().Single(u=>u.SelectedActorDuelOrigin is not null);var grant=Players(h)[0].SkillGrants.Grants.Single(x=>x.SkillId==Skill);Players(h)[0].SkillGrants.RemoveGrant(grant.GrantId);Settle(h);Require(h.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Any(e=>e.CardKind==CardKind.Duel),"Host-only source loss after issuance does not withdraw the real Use.");
        Require(!JsonSerializer.Serialize(new ProgramSkillFrame(1,0,"old","old","old",0,[],[])).Contains("DamageAppearanceReceipt"),"Old null damage receipt omitted.");Require(!JsonSerializer.Serialize(use with {SelectedActorDuelOrigin=null}).Contains("SelectedActorDuelOrigin"),"Old null origin is omitted from serialization.");
    }
    static void Activate(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");
    static void Skip(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");
    static void Answer(GameEngine g,Func<PromptChoice,bool> choose){var p=P(g)!;Accept(g,new AnswerPromptCommand(p.PlayerSeat,p.PromptId,p.Choices.First(choose).Id,g.Revision));}
    static void Reach(GameEngine g,Func<PendingDecision,bool> goal){for(var i=0;i<100;i++){if(P(g)is{}p&&goal(p))return;Accept(g,new AdvanceOneStepCommand(g.Revision));}throw new InvalidOperationException("No requested prompt: "+P(g)?.Prompt);}
    static IEnumerable<LegalAction> Actions(GameEngine g)=>g.GetHumanLegalActions().Where(a=>a.ProgramSkillId==Skill);
    static void Use(GameEngine g,int actor)=>Accept(g,new UseProgramSkillCommand(0,Skill,Binding,[],[actor],g.Revision,P(g)!.PromptId));
    static void Driver(GameEngine g,string id,int[]?targets=null)=>Accept(g,new UseProgramSkillCommand(0,"fixture:hx-driver",id,[],targets??[],g.Revision,P(g)!.PromptId));
    static CharacterState[] Players(GameEngine g)=>((IReadOnlyList<CharacterState>)typeof(GameEngine).GetField("_players",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(g)!).ToArray();
    static void Settle(GameEngine g){for(var i=0;i<100;i++){if(P(g)is{Kind:DecisionKind.PlayCard,PlayerSeat:0} && !g.ResolutionStack.Any(f=>f is CardUseFrame or ProgramSkillFrame) || g.State.Status==EngineStatus.Completed)return;if(P(g)?.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="skip")==true)Skip(g);else if(P(g) is{PlayerSeat:0,Kind:DecisionKind.RespondSlash or DecisionKind.Nullification or DecisionKind.RescueDying})Answer(g,c=>c.Cards.Count==0);else Accept(g,new AdvanceOneStepCommand(g.Revision));}throw new InvalidOperationException("Did not settle: "+P(g)?.Prompt);}
    static void Cold(GameEngine g,ContentRegistry r){var cp=g.CreateCheckpoint();var x=GameReplay.Restore(GameCheckpointJson.Deserialize(GameCheckpointJson.Serialize(cp)),r);Require(x.Revision==g.Revision&&JsonSerializer.Serialize(x.CreateCheckpoint().Commands)==JsonSerializer.Serialize(cp.Commands),"Cold accepted commands are identical.");for(var i=0;i<4;i++)Require(JsonSerializer.Serialize(x.CreateSnapshot(i))==JsonSerializer.Serialize(g.CreateSnapshot(i)),"Cold four viewer projections match.");}
    static void Accept(GameEngine g,GameCommand command){var before=GameCheckpointJson.Serialize(g.CreateCheckpoint());try{var x=g.Submit(command);Require(x.Accepted,x.Error?.Message??"Rejected.");}catch(Exception ex){if(Environment.GetEnvironmentVariable("CARD_HX_EVIDENCE") is{Length:>0} root){var d=Path.Combine(root,"actual-submit-"+(++FailSequence));Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint-before.json"),before);File.WriteAllText(Path.Combine(d,"attempt.json"),JsonSerializer.Serialize(command,command.GetType()));File.WriteAllText(Path.Combine(d,"post-failure-observed-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));File.WriteAllText(Path.Combine(d,"exception.txt"),ex.ToString());}throw;}}
    static void Evidence(GameEngine g,string label){if(Environment.GetEnvironmentVariable("CARD_HX_EVIDENCE") is not{Length:>0}root)return;var d=Path.Combine(root,label);Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint.json"),GameCheckpointJson.Serialize(g.CreateCheckpoint()));File.WriteAllText(Path.Combine(d,"trusted-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));for(var i=0;i<4;i++)File.WriteAllText(Path.Combine(d,"view-"+i+".json"),JsonSerializer.Serialize(g.CreateSnapshot(i)));}
    static void Reject(string members){var rejected=false;try{Load("fixture:hx-bad",members);}catch(InvalidOperationException){rejected=true;}Require(rejected,"Malformed new resource/activation rejects during load.");}
    static SkillProgram Load(string id,string members)=>SkillProgramCatalog.Load("{\"schemaVersion\":"+SkillProgramCatalog.RulesSchemaVersion+",\"skills\":[{\"id\":\""+id+"\",\"revision\":1,"+members+"}]}","{\"schemaVersion\":3,\"skills\":{\""+id+"\":{\"name\":\"fixture\",\"description\":\"fixture\"}}}").Programs[id];
    static string Act(string id,string effects,int targets=0)=>"{\"id\":\""+id+"\",\"minCards\":0,\"maxCards\":0,\"minTargets\":"+targets+",\"maxTargets\":"+targets+",\"targetKind\":\"anyLiving\",\"usesPerTurn\":null,\"effects\":"+effects+"}";
    static(GameEngine,ContentRegistry) Start(string kind="dodge",bool black=false,bool gain=false,int hp=6,bool jizhi=false,bool kongcheng=false,bool extra=false,bool native=false,bool actorBan=false,bool gainDying=false,bool completed=false,bool hongyan=false)
    {var r=ContentRegistry.Build(new StandardContentPackage(),new Fixture(kind,black,gain,hp,jizhi,kongcheng,extra,native,actorBan,gainDying,completed,hongyan));var g=GameEngine.CreateStandard(new GameOptions{Seed=31,PlayerCount=4,HumanSeat=native?3:0,HumanRole=native?Role.Rebel:Role.Lord,ModeId="identity:classic-hx",UseInteractiveSetup=!native,AdvanceAfterHumanCommands=false,MaxTurns=5,UseInteractiveDiscard=false},r);Accept(g,new StartGameCommand());if(!native){Reach(g,p=>p.Kind==DecisionKind.SelectGeneral);Accept(g,new SelectGeneralCommand(0,"fixture:hx",g.Revision,P(g)!.PromptId));Settle(g);if(hp==1){Driver(g,"lower");Settle(g);}}return(g,r);}
    sealed class Fixture(string kind,bool black,bool gain,int hp,bool jizhi,bool kongcheng,bool extra,bool native,bool actorBan,bool gainDying,bool completed,bool hongyan):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture-hx",new(1,0,0),[]);
        public void Register(IContentRegistryBuilder b)
        {
            try{typeof(StandardContentPackage).Assembly.GetType("CardGame.Content.Standard.BoundaryHuaXiongContent")!.GetMethod("Register",BindingFlags.NonPublic|BindingFlags.Static)!.Invoke(null,[b]);}catch(TargetInvocationException ex){throw new InvalidOperationException(ex.InnerException?.ToString(),ex.InnerException);}
            var classic=ContentRegistry.Build(new StandardContentPackage(),new StandardActiveSkillExpansionPackage(true),new StandardRescueSkillExpansionPackage(),new StandardClassicGeneralPackage());
            if(hongyan)b.AddSkill(classic.GetSkill("classic:hongyan"));if(jizhi)b.AddSkill(classic.GetSkill("classic:jizhi"));if(kongcheng)b.AddSkill(classic.GetSkill("classic:kongcheng"));if(extra)b.AddSkill(classic.GetSkill("classic:dangxian"));
            var driver=Act("lower","[{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":1}]")+","+Act("cardless","[{\"op\":\"damage\",\"target\":\"owner\",\"sourceRef\":{\"kind\":\"selectedTarget\"},\"amount\":1}]",1)+","+Act("legacy-duel","[{\"op\":\"startVirtualDuel\",\"target\":\"owner\"}]",2)+","+Act("empty","[{\"op\":\"discardOwnedZoneCards\",\"target\":\"owner\",\"zones\":[\"hand\"]}]")+","+Act("ban","[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"duel\"],\"actionTypes\":[\"use\"]}]",1);
            b.AddSkill(new("fixture:hx-driver","driver","driver"){Program=Load("fixture:hx-driver","\"activations\":["+driver+"]")});
            if(gain)b.AddSkill(new("fixture:hx-gain","gain","gain"){Program=Load("fixture:hx-gain","\"triggers\":[{\"id\":\"gain\",\"window\":\"cardsGained\",\"subject\":\"owner\",\"destinationZones\":[\"hand\"],\"movementOccurrence\":\"perBatch\",\"usageScope\":\"turn\",\"usageLimit\":1,\"optional\":true,\"effects\":[{\"op\":\"selectOwnedCards\",\"target\":\"owner\",\"zones\":[\"hand\"],\"amount\":1,\"resultBind\":\"selected\"},{\"op\":\"moveBoundCards\",\"target\":\"owner\",\"sourceBind\":\"selected\",\"destination\":\"discardPile\"}"+(gainDying?",{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":1}":"")+"]}]")});
            if(gainDying)b.AddSkill(new("fixture:hx-hp","hp","hp"){Program=Load("fixture:hx-hp","\"triggers\":[{\"id\":\"pause\",\"window\":\"afterHpRecovered\",\"subject\":\"owner\",\"optional\":true,\"usageScope\":\"turn\",\"usageLimit\":1,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]")});
            if(completed)b.AddSkill(new("fixture:hx-completed","completed","completed"){Program=Load("fixture:hx-completed","\"triggers\":[{\"id\":\"pause\",\"window\":\"cardUseCompleted\",\"ownerRelation\":\"target\",\"cardKinds\":[\"duel\"],\"optional\":true,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]")});
            if(jizhi)b.AddSkill(new("fixture:hx-no-counter","no counter","no counter"){Program=Load("fixture:hx-no-counter", "\"triggers\":[{\"id\":\"ban\",\"window\":\"playPhaseStarting\",\"subject\":\"owner\",\"turnOwnerScope\":\"otherLiving\",\"optional\":false,\"effects\":[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"nullification\"],\"actionTypes\":[\"use\"]}]}]")});
            if(actorBan)b.AddSkill(new("fixture:hx-ban","ban","ban"){Program=Load("fixture:hx-ban", "\"triggers\":[{\"id\":\"ban\",\"window\":\"playPhaseStarting\",\"subject\":\"owner\",\"turnOwnerScope\":\"otherLiving\",\"optional\":false,\"effects\":[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"duel\"],\"actionTypes\":[\"use\"]}]}]")});
            var extras=new[]{Yao}.Concat(hongyan?["classic:hongyan"]:Array.Empty<string>()).Concat(gainDying?["fixture:hx-hp"]:Array.Empty<string>()).Concat(completed?["fixture:hx-completed"]:Array.Empty<string>()).Concat(!native?["fixture:hx-driver"]:Array.Empty<string>()).Concat(gain?["fixture:hx-gain"]:Array.Empty<string>()).Concat(kongcheng?["classic:kongcheng"]:Array.Empty<string>()).Concat(extra?["classic:dangxian"]:Array.Empty<string>()).ToArray();
            b.AddGeneral(new("fixture:hx","华雄","supporter",Skill,"qun",hp,extras,GeneralGender.Male){InitialHp=hp});
            for(var i=1;i<4;i++)b.AddGeneral(new("fixture:hx-"+i,"其他"+i,"supporter",native?Skill:"standard:none","wei",6,new[]{Yao}.Concat(actorBan&&i==1?["fixture:hx-ban"]:Array.Empty<string>()).Concat(jizhi?["classic:jizhi","fixture:hx-no-counter"]:Array.Empty<string>()).ToArray()));
            b.AddDeck(new("fixture:hx-deck","固定",4,0,[]){PhysicalCards=Enumerable.Range(0,96).Select(i=>new ContentDeckPhysicalCard("standard:"+kind,kind=="lightning"&&i==55?Suit.Spade:black?Suit.Spade:Suit.Heart,i%13+1)).ToArray()});
            b.AddMode(new("identity:classic-hx","固定",4,4,new Dictionary<string,int>{{nameof(Role.Lord),1},{nameof(Role.Loyalist),1},{nameof(Role.Rebel),2}},"fixture:hx-deck",GeneralCandidateCount:4,GeneralPoolIds:["fixture:hx","fixture:hx-1","fixture:hx-2","fixture:hx-3"]));
        }
    }
}
