using System.Reflection;
using System.Text.Json;
using CardGame.Core;
using CardGame.Content.Standard;
using static BoundaryLiDianChecks;
internal static class BoundaryLuBuChecks
{
    private const string Skill="boundary:liyu-current";
    private static readonly Lazy<ContentRegistry> Classic=new(()=>ContentRegistry.Build(new StandardContentPackage(),new StandardActiveSkillExpansionPackage(true),new StandardRescueSkillExpansionPackage(),new StandardClassicGeneralPackage()));
    public static void QualificationAndParser()
    {
        var valid="\"triggers\":[{\"id\":\"x\",\"window\":\"afterDamageApplied\",\"subject\":\"damageSource\",\"damageOccurrence\":\"perDamage\",\"optional\":true,\"effects\":[{\"op\":\"obtainDamageTargetCardAndResolveCategory\",\"target\":\"owner\"}]}]";
        Require(Load("fixture:parse",valid).Triggers.Count==1,"Exact compound parses.");Require(!JsonSerializer.Serialize(new ProgramSkillFrame(1,0,"old","old","old",0,[],[])).Contains("DamageTargetObtain")&&!JsonSerializer.Serialize(new CardUseFrame(1,0,1,CardKind.Slash,[1])).Contains("DamageTargetDuelOrigin"),"Old null additive owning fields remain omitted.");
        foreach(var bad in new[]{valid.Replace("afterDamageApplied","beforeDamageApplied"),valid.Replace("damageSource","owner"),valid.Replace("perDamage","perCardUse"),valid.Replace("\"optional\":true","\"optional\":false"),valid.Replace("\"target\":\"owner\"","\"target\":\"selectedTarget\""),valid.Replace("\"target\":\"owner\"","\"target\":\"owner\",\"amount\":1"),"\"activations\":["+Act("bad","[{\"op\":\"obtainDamageTargetCardAndResolveCategory\",\"target\":\"owner\"}]")+"]"}){var rejected=false;try{Load("fixture:bad",bad);}catch(InvalidOperationException){rejected=true;}Require(rejected,"Wrong compound composition is rejected.");}
        var(g,r)=Start();Driver(g,"cardless",[1]);Settle(g);Require(!g.Events.Select(e=>e.Payload).OfType<ProgramSkillStartedEvent>().Any(e=>e.SkillId==Skill),"No-card damage cannot produce obtain.");Cold(g,r);
        Driver(g,"virtual",[1]);Offer(g);Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");Settle(g);Require(!g.CardMovements.Any(m=>m.Reason.Value=="skill-program.damage-target-obtain.obtain"),"Optional decline makes no receipt.");Cold(g,r);
        var(s,sr)=Start(fire:true);Driver(s,"chain",[0]);Settle(s);Driver(s,"chain",[1]);Settle(s);Slash(s);Finish(s);Require(s.Events.Select(e=>e.Payload).OfType<ProgramBindingResolvedEvent>().Count(e=>e.SkillId==Skill)==1,"Real fire Slash chained self-victim does not offer obtain.");Cold(s,sr);
    }
    public static void HejAndPrintedCategory()
    {
        foreach(var kind in new[]{"classic:silver-lion","standard:offensive_horse","classic:wooden-ox"})
        {
            var(g,r)=Start(equipment:kind,protect:kind=="classic:silver-lion");Driver(g,"equip",[1]);Settle(g);var card=g.State.Players[1].Equipment.Single();Slash(g);Offer(g);Activate(g);ObtainPrompt(g);Cold(g,r);
            var p=P(g)!;Require(p.Choices.Any(c=>c.Parameters["source-zone"]=="Hand"&&c.Cards.Count==0)&&p.Choices.Any(c=>c.Cards.Contains(card.Id)),"Hidden hand opaque/public equipment offered for actual Obtain, including protected equipment.");
            AtomicReject(g,new AnswerPromptCommand(0,p.PromptId,new ChoiceId("foreign"),g.Revision));Answer(g,c=>c.Cards.Contains(card.Id));DuelPrompt(g);Require(P(g)!.PlayerSeat==1,"Victim owns required Duel choice.");Cold(g,r);Answer(g,c=>c.Targets.SequenceEqual([2]));Settle(g);Require(Moves(g,card.Id).Count(m=>m.Reason.Value=="skill-program.damage-target-obtain.obtain"&&m.From==CardLocation.Equipment(1)&&m.To==CardLocation.Hand(0))==1,"Equipment obtained directly once.");Require(g.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Any(e=>e.CardKind==CardKind.Duel&&e.SourceSeat==0),"Every printed equipment category issues real Duel.");Cold(g,r);
        }
        var(h,hr)=Start();Driver(h,"equip",[0]);Settle(h);var id=h.State.Players[0].Equipment.Single().Id;Driver(h,"give-board",[1]);Reach(h,p=>p.Choices.Any(c=>c.Cards.Contains(id)));Answer(h,c=>c.Cards.Contains(id));Settle(h);Slash(h);Offer(h);Activate(h);ObtainPrompt(h);var slot=h.CreateSnapshot(1).Players[1].Hand.Select((c,i)=>(c,i)).Single(x=>x.c.Id==id).i;var choice=P(h)!.Choices.Single(c=>c.Parameters["source-zone"]=="Hand"&&c.Parameters["slot-index"]==slot.ToString());Require(choice.Cards.Count==0,"Hand equipment remains opaque before obtaining.");Answer(h,c=>c.Id==choice.Id);DuelPrompt(h);Cold(h,hr);Answer(h,c=>c.Targets.SequenceEqual([2]));Settle(h);Require(h.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Any(e=>e.CardKind==CardKind.Duel),"Printed hand equipment takes equipment branch.");Cold(h,hr);
        var(j,jr)=Start(judgment:true);Play(j,j.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Indulgence&&a.TargetSeat==1));Settle(j);var judge=j.State.Players[1].Judgment.Single();Slash(j);Offer(j);Activate(j);ObtainPrompt(j);var before=j.State.Players[1].HandCount;Answer(j,c=>c.Cards.Contains(judge.Id));Settle(j);Require(j.State.Players[0].Hand.Any(c=>c.Id==judge.Id)&&j.State.Players[1].HandCount==before+1,"Public Judgment non-equipment is obtained then original victim draws once.");Cold(j,jr);
        var(o,or)=Start(child:"outside");Cold(o,or);var zones=(CardZoneStore)typeof(GameEngine).GetField("_cardZones",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(o)!;var generated=new Card(1000,CardKind.GeneralWeapon,Suit.None,0){IsGeneralWeapon=true,PrintedName="host general weapon",PrintedAttackRange=3};zones.AddGeneratedCard(generated);((HashSet<int>)typeof(GameEngine).GetField("_generatedPhysicalCardIds",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(o)!).Add(generated.Id);zones.MoveMany([generated.Id],CardLocation.OutsideGame,CardLocation.Equipment(1));Slash(o);Offer(o);Activate(o);ObtainPrompt(o);Answer(o,c=>c.Cards.Contains(generated.Id));Reach(o,p=>p.SkillPrompt?.SkillId=="fixture:lb-outside");Activate(o);Settle(o);Require(Moves(o,generated.Id).Single().To==CardLocation.OutsideGame&&!o.CardMovements.Any(m=>m.Reason.Value=="skill-program.damage-target-obtain.benefit-draw")&&!o.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Any(e=>e.CardKind==CardKind.Duel),"Host-injected weapon actual normalization to OutsideGame creates no obtain benefit.");Require(o.CardMovements.Any(m=>m.Reason.Value=="skill-program.fixture:lb-outside.Draw"),"Exact actual OutsideGame movement observer executes without creating an obtained-card reward.");Console.WriteLine("OutsideGame preparation uses host injection; its actual movement is audited separately from replay fixtures.");
    }
    public static void PaidChildrenAndLifetime()
    {
        foreach(var child in new[]{"gain-draw","gain-loss","loss","death","victim-death"})
        {
            var(g,r)=Start(child:child,rebel:child=="death");Slash(g);Offer(g);Activate(g);ObtainPrompt(g);Answer(g,c=>c.Parameters["source-zone"]=="Hand");Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:lb-child");var receipt=g.ResolutionStack.OfType<ProgramSkillFrame>().Single(f=>f.SkillId==Skill).DamageTargetObtain!.Receipt!;Require(receipt.To==CardLocation.Hand(0)&&!receipt.IsEquipment,"Receipt before real gain child freezes exact movement/category.");Cold(g,r);Evidence(g,"paid-"+child);var before=g.State.Players[1].HandCount;Activate(g);if(child=="loss"){Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("advanced-value")==Skill));Answer(g,c=>c.Parameters.GetValueOrDefault("advanced-value")==Skill);}FinishCurrent(g);Evidence(g,"paid-finished-"+child);
            Require(Moves(g,receipt.CardId).Count(m=>m.Reason.Value=="skill-program.damage-target-obtain.obtain")==1,"Child never obtains twice.");if(child=="death")Require(!g.State.Players[0].IsAlive&&g.State.Status!=EngineStatus.Completed&&g.State.Players[1].HandCount==before+1,"Actual non-equipment paid owner death retains living victim draw.");else if(child=="victim-death")Require(!g.State.Players[1].IsAlive&&!g.CardMovements.Any(m=>m.Reason.Value=="skill-program.damage-target-obtain.benefit-draw"),"Actual victim death makes no reward draw.");else Require(g.State.Players[1].HandCount==before+1,"Paid source removal/child returns retain one benefit.");Cold(g,r);
        }
        var(m,mr)=Start(child:"discard");Driver(m,"equip",[1]);Settle(m);var moved=m.State.Players[1].Equipment.Single().Id;Slash(m);Offer(m);Activate(m);ObtainPrompt(m);Answer(m,c=>c.Cards.Contains(moved));Reach(m,p=>p.SkillPrompt?.SkillId=="fixture:lb-child");Cold(m,mr);Activate(m);Reach(m,p=>p.Choices.Any(c=>c.Cards.Contains(moved)));Answer(m,c=>c.Cards.Contains(moved));DuelPrompt(m);Require(!m.State.Players[0].Hand.Any(c=>c.Id==moved),"Actual gain child has moved obtained equipment away before branch selection.");Cold(m,mr);Answer(m,c=>c.Targets.SequenceEqual([2]));Settle(m);Require(Moves(m,moved).Count(x=>x.Reason.Value=="skill-program.damage-target-obtain.obtain")==1&&m.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Count(e=>e.CardKind==CardKind.Duel)==1,"Frozen printed category issues Duel once without taking moved entity back.");Cold(m,mr);
        var(q,qr)=Start(child:"rescue");Driver(q,"equip",[1]);Settle(q);var equip=q.State.Players[1].Equipment.Single().Id;Slash(q);Offer(q);Activate(q);ObtainPrompt(q);Answer(q,c=>c.Cards.Contains(equip));Reach(q,p=>p.SkillPrompt?.SkillId=="fixture:lb-child");Activate(q);Reach(q,p=>p.Kind==DecisionKind.RescueDying&&p.PlayerSeat==0);Require(q.State.Players[0].Hp==0,"Paid obtain actual HP loss pauses at zero HP.");Cold(q,qr);var peach=P(q)!.Choices.First(c=>c.Cards.Count==1).Cards.Single();Answer(q,c=>c.Cards.SequenceEqual([peach]));Reach(q,p=>p.SkillPrompt?.SkillId=="fixture:lb-hp");Cold(q,qr);Activate(q);DuelPrompt(q);Cold(q,qr);Answer(q,c=>c.Targets.SequenceEqual([2]));Settle(q);Require(q.State.Players[0].IsAlive&&Moves(q,equip).Count(x=>x.Reason.Value=="skill-program.damage-target-obtain.obtain")==1&&q.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Count(e=>e.CardKind==CardKind.Duel)==1,"Actual entity Peach and recovery observer return to one paid equipment Duel.");Cold(q,qr);
        var(s,sr)=Start(child:"gain-draw");Driver(s,"equip",[1]);Settle(s);var id=s.State.Players[1].Equipment.Single().Id;Slash(s);Offer(s);Activate(s);ObtainPrompt(s);Answer(s,c=>c.Cards.Contains(id));Reach(s,p=>p.SkillPrompt?.SkillId=="fixture:lb-child");var grant=Players(s)[0].SkillGrants.Grants.Single(x=>x.SkillId==Skill);Players(s)[0].SkillGrants.RemoveGrant(grant.GrantId);Skip(s);DuelPrompt(s);Answer(s,c=>c.Targets.SequenceEqual([2]));Settle(s);Require(s.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Count(e=>e.CardKind==CardKind.Duel)==1,"Host-only source removal after receipt preserves one real Duel.");Console.WriteLine("Host injection source loss is separate from accepted cold replay fixtures.");
        var(h,hr)=Start();Driver(h,"equip",[1]);Settle(h);Slash(h);Offer(h);Activate(h);ObtainPrompt(h);Answer(h,c=>c.Parameters["source-zone"]=="Equipment");DuelPrompt(h);Answer(h,c=>c.Targets.SequenceEqual([2]));Reach(h,p=>p.Kind==DecisionKind.RespondSlash&&p.PlayerSeat==2);var issued=Players(h)[0].SkillGrants.Grants.Single(x=>x.SkillId==Skill);Players(h)[0].SkillGrants.RemoveGrant(issued.GrantId);Settle(h);Require(h.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Count(e=>e.CardKind==CardKind.Duel)==1&&h.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Count(e=>e.CardKind==CardKind.Duel)==1,"Host-only source removal after real issuance never repeats or withdraws Duel.");
    }
    public static void VictimChooserAndLegality()
    {
        var(g,r)=Start();Driver(g,"equip",[1]);Settle(g);Slash(g);Offer(g);Activate(g);ObtainPrompt(g);Answer(g,c=>c.Parameters["source-zone"]=="Equipment");DuelPrompt(g);var p=P(g)!;Require(p.PlayerSeat==1&&p.Choices.Count==2&&p.Choices.All(c=>c.Targets.Count==1&&!c.Targets.Contains(0)&&!c.Targets.Contains(1)),"Victim chooses exactly one legal other; no decline.");Cold(g,r);AtomicReject(g,new AnswerPromptCommand(0,p.PromptId,p.Choices[0].Id,g.Revision));AtomicReject(g,new AnswerPromptCommand(1,p.PromptId,new ChoiceId("damage-target-duel.frame-foreign.seat-0"),g.Revision));Answer(g,c=>c.Targets.SequenceEqual([2]));Settle(g);Cold(g,r);
        var(b,br)=Start();Driver(b,"duel-ban");Settle(b);Driver(b,"equip",[1]);Settle(b);Slash(b);Offer(b);Activate(b);ObtainPrompt(b);Answer(b,c=>c.Parameters["source-zone"]=="Equipment");Settle(b);Require(!b.Events.Select(e=>e.Payload).OfType<CardUseDeclaredEvent>().Any(e=>e.CardKind==CardKind.Duel),"No legal target ends paid equipment branch without an empty prompt.");Cold(b,br);
    }
    public static void NestedDuelAndNative()
    {
        var(g,r)=Start();Driver(g,"hurt-target",[2]);Settle(g);Driver(g,"equip",[1]);Settle(g);Slash(g);Offer(g);Activate(g);ObtainPrompt(g);Answer(g,c=>c.Parameters["source-zone"]=="Equipment");DuelPrompt(g);Answer(g,c=>c.Targets.SequenceEqual([2]));Reach(g,p=>p.Kind==DecisionKind.RespondSlash&&p.PlayerSeat==2);Cold(g,r);Evidence(g,"issued-nested-duel");Accept(g,new AdvanceOneStepCommand(g.Revision));Require(P(g) is {Kind:DecisionKind.RespondSlash,PlayerSeat:2}&&g.ResolutionStack.OfType<CardUseFrame>().Last().Continuations.Duel?.SuccessfulSlashResponses==1,"First real Slash leaves Wushuang second response pending.");Cold(g,r);Accept(g,new AdvanceOneStepCommand(g.Revision));Require(g.Events.Select(e=>e.Payload).OfType<DuelResponseEvent>().Count(e=>e.ResponderSeat==2&&e.UsedSlash)==2,"Classic Wushuang consumes two actual AI Slash responses before handing response to actor.");Cold(g,r);Evidence(g,"wushuang-first-response");Settle(g);Require(g.Events.Select(e=>e.Payload).OfType<DamageAppliedEvent>().Count()>1&&g.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Count(e=>e.CardKind==CardKind.Duel)==1,"True nested Duel damage completes and returns to outer Slash once.");Cold(g,r);
        var(n,nr)=Start(nullify:true,jizhi:true);Driver(n,"equip",[1]);Settle(n);Slash(n);Offer(n);Activate(n);ObtainPrompt(n);Answer(n,c=>c.Parameters["source-zone"]=="Equipment");DuelPrompt(n);Answer(n,c=>c.Targets.SequenceEqual([2]));Reach(n,p=>p.SkillPrompt?.SkillId=="classic:jizhi");Activate(n);Reach(n,p=>p.Kind==DecisionKind.Nullification&&p.PlayerSeat==0);Cold(n,nr);Answer(n,c=>c.Cards.Count==1);Finish(n);Require(n.Events.Select(e=>e.Payload).OfType<ProgramBindingStartedEvent>().Any(e=>e.SkillId=="classic:jizhi")&&n.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Any(e=>e.CardKind==CardKind.Duel),"Real Jizhi and entity Nullification preserve false typed return.");Require(n.Events.Select(e=>e.Payload).OfType<DamageAppliedEvent>().Count()==1,"Nullified Duel makes no additional damage.");Cold(n,nr);Evidence(n,"nullified-nested-duel");
        var(ai,ar)=Start(native:true);for(var i=0;i<160&&!ai.CardMovements.Any(m=>m.Reason.Value=="skill-program.damage-target-obtain.obtain");i++)Accept(ai,new AdvanceOneStepCommand(ai.Revision));Require(ai.CardMovements.Any(m=>m.Reason.Value=="skill-program.damage-target-obtain.obtain"),"Formal native AI accepts optional obtain.");Cold(ai,ar);Evidence(ai,"native-obtain");
    }
    private static void FinishCurrent(GameEngine g){for(var i=0;i<150;i++){if(g.State.Status==EngineStatus.Completed||!g.ResolutionStack.Any(f=>f is CardUseFrame or ProgramSkillFrame))return;Step(g);}throw new InvalidOperationException("Compound did not settle.");}
    private static void ObtainPrompt(GameEngine g)=>Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="damage-target-obtain"));
    private static void DuelPrompt(GameEngine g)=>Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="damage-target-duel"));
    private static void Skip(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");
    private static void AtomicReject(GameEngine g,GameCommand cmd){var before=GameCheckpointJson.Serialize(g.CreateCheckpoint());Require(!g.Submit(cmd).Accepted&&before==GameCheckpointJson.Serialize(g.CreateCheckpoint()),"Foreign/stale/chooser rejected atomically.");}
    private static IReadOnlyList<CharacterState> Players(GameEngine g)=>(IReadOnlyList<CharacterState>)typeof(GameEngine).GetField("_players",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(g)!;
    private static IEnumerable<CardMovementRecord> Moves(GameEngine g,int id)=>g.CardMovements.Where(m=>m.CardId==id);
    private static void Cold(GameEngine g,ContentRegistry r){ReplayFourViews(g,r);var cold=GameReplay.Restore(GameCheckpointJson.Deserialize(GameCheckpointJson.Serialize(g.CreateCheckpoint())),r);Require(JsonSerializer.Serialize(g.CreateSnapshot(-1))==JsonSerializer.Serialize(cold.CreateSnapshot(-1)),"Spectator cold projection matches.");foreach(var v in Enumerable.Range(0,4))foreach(var p in g.CreateSnapshot(v).Players)if(p.Seat!=v)Require(p.Hand.Count==0,"Other players' hand entities remain private.");}
    private static PendingDecision? P(GameEngine g)=>g.CreateSnapshot(0).PendingDecision??g.CreateSnapshot(1).PendingDecision??g.CreateSnapshot(2).PendingDecision??g.CreateSnapshot(3).PendingDecision;
    private static void Answer(GameEngine g,Func<PromptChoice,bool> predicate){var p=P(g)!;Accept(g,new AnswerPromptCommand(p.PlayerSeat,p.PromptId,p.Choices.First(predicate).Id,g.Revision));}
    private static void Activate(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");
    private static void Driver(GameEngine g,string id,int[]?targets=null)=>Accept(g,new UseProgramSkillCommand(0,"fixture:lb-driver",id,[],targets??[],g.Revision,P(g)!.PromptId));
    private static void Play(GameEngine g,LegalAction a)=>Accept(g,new PlayCardCommand(0,a.CardId!.Value,a.TargetSeats.Count>0?a.TargetSeats:[a.TargetSeat!.Value],g.Revision,P(g)!.PromptId,a.PlayedCardKind){ConversionSource=a.ConversionSource,AdditionalConversionSources=a.AdditionalConversionSources});
    private static void Slash(GameEngine g)=>Play(g,g.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.Slash&&a.TargetSeat==1));
    private static void Offer(GameEngine g)=>Reach(g,p=>p.SkillPrompt?.SkillId==Skill&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));
    private static void Reach(GameEngine g,Func<PendingDecision,bool> predicate){for(var i=0;i<100;i++){if(P(g)is{}p&&predicate(p))return;Step(g);}throw new InvalidOperationException("Fixed fixture did not reach prompt: "+P(g)?.Prompt);}
    private static void Settle(GameEngine g)=>Reach(g,p=>p.Kind==DecisionKind.PlayCard&&p.PlayerSeat==0);
    private static void Finish(GameEngine g){for(var i=0;i<150;i++){if(g.State.Status==EngineStatus.Completed||P(g)is{Kind:DecisionKind.PlayCard,PlayerSeat:0})return;Step(g);}throw new InvalidOperationException("Finite fixture did not settle.");}
    private static void Step(GameEngine g)
    {
        var p=P(g);
        if(p is{Kind:DecisionKind.ProgramTrigger,PlayerSeat:0})
        {
            if(p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="skip"))Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");
            else if(p.Choices.Any(c=>c.Parameters.GetValueOrDefault("advanced-value")==Skill))Answer(g,c=>c.Parameters.GetValueOrDefault("advanced-value")==Skill);
            else if(p.Choices.Any(c=>c.Parameters.GetValueOrDefault("advanced-value")=="finish"))Answer(g,c=>c.Parameters.GetValueOrDefault("advanced-value")=="finish");
            else Answer(g,_=>true);
        }
        else if(p is{Kind:DecisionKind.DiscardCards,PlayerSeat:0})Accept(g,new DiscardCardsCommand(0,p.ValidCardIds.Take(p.RequiredCardCount).ToArray(),p.PromptId,g.Revision));
        else if(p is{Kind:DecisionKind.RescueDying or DecisionKind.RespondSlash or DecisionKind.Nullification or DecisionKind.RespondDodge,PlayerSeat:0})Answer(g,c=>c.Cards.Count==0);
        else Accept(g,new AdvanceOneStepCommand(g.Revision));
    }
    private static int Attempt;
    private static void Accept(GameEngine g,GameCommand cmd)
    {var before=GameCheckpointJson.Serialize(g.CreateCheckpoint());try{BoundaryLiDianChecks.Accept(g,cmd);}catch(Exception ex){if(Environment.GetEnvironmentVariable("CARD_LB_EVIDENCE")is{Length:>0}root){var d=Path.Combine(root,"submit-failure-"+Interlocked.Increment(ref Attempt).ToString("D3"));Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint-before.json"),before);File.WriteAllText(Path.Combine(d,"attempt.json"),JsonSerializer.Serialize(cmd,cmd.GetType()));File.WriteAllText(Path.Combine(d,"faulted-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));File.WriteAllText(Path.Combine(d,"exception.txt"),ex.ToString());}throw;}}
    private static void Evidence(GameEngine g,string label){if(Environment.GetEnvironmentVariable("CARD_LB_EVIDENCE")is not{Length:>0}root)return;var d=Path.Combine(root,label);Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint.json"),GameCheckpointJson.Serialize(g.CreateCheckpoint()));File.WriteAllText(Path.Combine(d,"trusted-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));for(var i=-1;i<4;i++)File.WriteAllText(Path.Combine(d,"view-"+i+".json"),JsonSerializer.Serialize(g.CreateSnapshot(i)));}
    private static (GameEngine,ContentRegistry) Start(string equipment="standard:offensive_horse",bool judgment=false,string? child=null,bool fire=false,bool native=false,bool nullify=false,bool rebel=false,bool jizhi=false,bool protect=false)
    {
        var r=ContentRegistry.Build(new StandardContentPackage(),new Fixture(equipment,judgment,child,fire,native,nullify,jizhi,protect));var g=GameEngine.CreateStandard(new GameOptions{Seed=31,PlayerCount=4,HumanSeat=native?3:0,HumanRole=native||rebel?Role.Rebel:Role.Lord,ModeId="identity:classic-lb",UseInteractiveSetup=!native,AdvanceAfterHumanCommands=false,UseInteractiveDiscard=false,MaxTurns=5},r);Accept(g,new StartGameCommand());if(!native){Reach(g,p=>p.Kind==DecisionKind.SelectGeneral);Accept(g,new SelectGeneralCommand(0,"fixture:lb",g.Revision,P(g)!.PromptId));Settle(g);}return(g,r);
    }
    private static SkillProgram Load(string id,string members)=>SkillProgramCatalog.Load("{\"schemaVersion\":"+SkillProgramCatalog.RulesSchemaVersion+",\"skills\":[{\"id\":\""+id+"\",\"revision\":1,"+members+"}]}","{\"schemaVersion\":3,\"skills\":{\""+id+"\":{\"name\":\"fixture\",\"description\":\"fixture\"}}}").Programs[id];
    private static string Act(string id,string effects,int targets=0)=>"{\"id\":\""+id+"\",\"minCards\":0,\"maxCards\":0,\"minTargets\":"+targets+",\"maxTargets\":"+targets+",\"targetKind\":\"anyLiving\",\"usesPerTurn\":null,\"effects\":"+effects+"}";
    private sealed class Fixture(string equipment,bool judgment,string?child,bool fire,bool native,bool nullify,bool jizhi,bool protect):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture-lb",new(1,0,0),[]);
        public void Register(IContentRegistryBuilder b)
        {
            try{typeof(StandardClassicGeneralPackage).Assembly.GetType("CardGame.Content.Standard.BoundaryLuBuContent")!.GetMethod("Register",BindingFlags.Static|BindingFlags.NonPublic)!.Invoke(null,[b]);}catch(TargetInvocationException e){throw new InvalidOperationException(e.InnerException?.ToString(),e.InnerException);}
            if(equipment.StartsWith("classic:"))b.AddCard(Classic.Value.GetCard(equipment));b.AddSkill(Classic.Value.GetSkill("classic:wusheng"));b.AddSkill(Classic.Value.GetSkill("classic:wushuang"));if(jizhi)b.AddSkill(Classic.Value.GetSkill("classic:jizhi"));if(protect)b.AddSkill(Classic.Value.GetSkill("boundary:qicai-current"));
            var acts=Act("hurt-target","[{\"op\":\"loseHp\",\"target\":\"selectedTarget\",\"amount\":2}]",1)+","+Act("duel-ban","[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"duel\"],\"actionTypes\":[\"use\"]}]")+","+Act("equip","[{\"op\":\"useRandomDeckEquipment\",\"target\":\"owner\",\"resultBind\":\"equipment\"}]",1)+","+Act("hurt","[{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":1}]")+","+Act("cardless","[{\"op\":\"damage\",\"target\":\"selectedTarget\",\"amount\":1}]",1)+","+Act("virtual","[{\"op\":\"useVirtualSlash\",\"target\":\"selectedTarget\"}]",1)+","+Act("chain","[{\"op\":\"setChainedState\",\"target\":\"selectedTarget\",\"chained\":true}]",1)+","+Act("give-board","[{\"op\":\"selectAndMoveOwnedCard\",\"target\":\"owner\",\"chooserRef\":{\"kind\":\"owner\"},\"cardOwnerRef\":{\"kind\":\"owner\"},\"zones\":[\"equipment\"],\"count\":1,\"destination\":\"selectedTargetHand\",\"targetRef\":{\"kind\":\"selectedTarget\"},\"awaitMovementTriggers\":true}]",1);
            b.AddSkill(new("fixture:lb-driver","实际准备","实际准备"){Program=Load("fixture:lb-driver","\"activations\":["+acts+"]"),SelectionWeights=Enum.GetValues<Role>().ToDictionary(x=>x,x=>-100d)});
            if(child!=null)
            {
                var effect=child=="discard"?"{\"op\":\"selectOwnedCards\",\"target\":\"owner\",\"zones\":[\"hand\"],\"amount\":1,\"resultBind\":\"received\"},{\"op\":\"moveBoundCards\",\"target\":\"owner\",\"sourceBind\":\"received\",\"destination\":\"discardPile\",\"awaitMovementTriggers\":true}":child=="victim-death"?"{\"op\":\"selectTarget\",\"target\":\"owner\",\"targetKind\":\"otherLiving\"},{\"op\":\"loseHp\",\"target\":\"selectedTarget\",\"amount\":20}":child=="gain-draw"?"{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}":child=="rescue"?"{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":5}":child=="gain-loss"?"{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":1}":child=="steal"?"{\"op\":\"claimMovedCards\",\"target\":\"owner\"}":child=="loss"?"{\"op\":\"replaceSkillsOnAwakening\",\"target\":\"owner\",\"skillIds\":[\"standard:none\"]}":"{\"op\":\"loseHp\",\"target\":\"owner\",\"amount\":20}";
                var gain=true;
                b.AddSkill(new("fixture:lb-child","实际移动子窗","实际移动子窗"){Program=Load("fixture:lb-child","\"triggers\":[{\"id\":\"child\",\"window\":\""+(gain?"cardsGained":"cardsGained")+"\",\"subject\":\"owner\","+(gain?"\"destinationZones\":[\"hand\"],\"movementOccurrence\":\"perBatch\",":"")+"\"movementReasons\":[\"skill-program.damage-target-obtain."+(gain?"obtain":"obtain")+"\"],\"usageScope\":\"turn\",\"usageLimit\":1,\"optional\":true,\"effects\":["+effect+"]}]")});
                if(child=="rescue")b.AddSkill(new("fixture:lb-hp","实际桃回复观察","实际桃回复观察"){Program=Load("fixture:lb-hp","\"triggers\":[{\"id\":\"hp\",\"window\":\"afterHpRecovered\",\"subject\":\"owner\",\"optional\":true,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]")});
                if(child=="loss")for(var i=0;i<6;i++)b.AddSkill(new("fixture:lb-dummy"+i,"拥有技能"+i,"拥有技能"));
            }
            if(nullify)b.AddSkill(new("fixture:lb-no-counter","no counter","no counter"){Program=Load("fixture:lb-no-counter","\"triggers\":[{\"id\":\"ban\",\"window\":\"playPhaseStarting\",\"subject\":\"owner\",\"turnOwnerScope\":\"otherLiving\",\"optional\":false,\"effects\":[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"nullification\"],\"actionTypes\":[\"use\"]}]}]")});
            if(child=="outside")b.AddSkill(new("fixture:lb-outside","outside observer","outside observer"){Program=Load("fixture:lb-outside","\"triggers\":[{\"id\":\"observe\",\"window\":\"cardsMoved\",\"subject\":\"owner\",\"sourceZones\":[\"equipment\"],\"movementReasons\":[\"skill-program.damage-target-obtain.obtain\"],\"movementOccurrence\":\"perBatch\",\"optional\":true,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]")});
            var extra=new[]{"classic:wushuang"}.Concat(jizhi?["classic:jizhi"]:Array.Empty<string>()).Concat(!native?["fixture:lb-driver"]:Array.Empty<string>()).Concat(judgment||nullify||child=="rescue"?["classic:wusheng"]:Array.Empty<string>()).Concat(child is"discard"or"loss"or"death"or"gain-draw"or"gain-loss"or"victim-death"or"rescue"?["fixture:lb-child"]:Array.Empty<string>()).Concat(child=="rescue"?["fixture:lb-hp"]:Array.Empty<string>()).Concat(child=="loss"?Enumerable.Range(0,6).Select(i=>"fixture:lb-dummy"+i):Array.Empty<string>()).ToArray();
            b.AddGeneral(new("fixture:lb","公孙瓒","supporter",Skill,"qun",4,extra));
            for(var i=1;i<4;i++)b.AddGeneral(new("fixture:lb-"+i,"固定目标"+i,"supporter",native?Skill:"standard:none","wei",5,(protect&&i==1?new[]{"boundary:qicai-current"}:Array.Empty<string>()).Concat(nullify?["fixture:lb-no-counter"]:Array.Empty<string>()).Concat(child=="outside"&&i==1?["fixture:lb-outside"]:Array.Empty<string>()).ToArray()));
            b.AddDeck(new("fixture:lb-deck","固定实体",4,2,[]){PhysicalCards=Enumerable.Range(0,80).Select(i=>new ContentDeckPhysicalCard(nullify?"standard:nullification":child=="rescue"?"standard:peach":judgment?"standard:indulgence":fire?"standard:fire_slash":"standard:slash",Suit.Heart,7)).Concat(Enumerable.Range(0,8).Select(i=>new ContentDeckPhysicalCard(equipment,Suit.Club,4))).ToArray()});
            b.AddMode(new("identity:classic-lb","固定",4,4,new Dictionary<string,int>{{nameof(Role.Lord),1},{nameof(Role.Loyalist),1},{nameof(Role.Rebel),2}},"fixture:lb-deck",GeneralCandidateCount:4,GeneralPoolIds:["fixture:lb","fixture:lb-1","fixture:lb-2","fixture:lb-3"]));
        }
    }
}
