using System.Reflection;
using System.Text.Json;
using CardGame.Core;
using CardGame.Content.Standard;
internal static class BoundaryYuanShaoChecks
{
    const string Luanji="boundary:luanji-current", Xueyi="boundary:xueyi-current", Conversion="same-suit-pair-as-arrow-barrage";
    static int EvidenceSequence;
    public static void StartingPopulationAndQualification()
    {
        foreach(var count in new[]{4,8})
        {
            var(g,r)=Start(count:count);Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);
            Require(Yi(g)==count*2,"Actual GameStarting counts every qun participant including owner.");
            Require(g.Events.Select(e=>e.Payload).OfType<PlayerMarkerChangedEvent>().Count(e=>e.Marker==PlayerMarkerKind.Yi&&e.Delta>0)==1,"Exactly one actual initial grant.");
            Cold(g,r);Witness(g,"initial-"+count);Skip(g);Play(g);Require(Limit(g)==g.State.Players[0].Hp+count*2,"Current marker aggregate contributes to actual HandLimit.");
            // Source identity loss/regrant is a host audit; it does not fabricate a new GameStarting.
            var player=Players(g)[0];var grant=player.SkillGrants.Grants.Single(x=>x.SkillId==Xueyi);player.SkillGrants.RemoveGrant(grant.GrantId);
            Require(Yi(g)==count*2&&Limit(g)==g.State.Players[0].Hp,"HOST: losing enabled lord source preserves marker fact and removes limit.");
            player.SkillGrants.Grant(grant);var role=player.Role;typeof(CharacterState).GetProperty("Role")!.SetValue(player,Role.Rebel);Require(Limit(g)==g.State.Players[0].Hp&&Yi(g)==count*2,"HOST live loss of lord qualification stops marker contribution without clearing facts.");typeof(CharacterState).GetProperty("Role")!.SetValue(player,role);Require(Limit(g)==g.State.Players[0].Hp+count*2,"HOST: restored exact source queries live aggregate.");
        }
        var(god,gr)=Start(god:true);Reach(god,p=>p.Kind==DecisionKind.SelectFaction);Require(!god.Events.Select(e=>e.Payload).OfType<PlayerMarkerChangedEvent>().Any(e=>e.Marker==PlayerMarkerKind.Yi),"Actual god faction selection precedes GameStarting marker facts.");Cold(god,gr);Answer(god,c=>c.Parameters.GetValueOrDefault("faction-id")=="qun");Reach(god,p=>p.SkillPrompt?.SkillId==Xueyi);Require(Yi(god)==4&&god.Events.Select(e=>e.Payload).OfType<GodFactionSelectedEvent>().Single().FactionId=="qun","Actual effective god faction and one other qun participant count as two; two wei participants do not.");Cold(god,gr);Witness(god,"actual-god-mixed-population");
        var(large,larger)=Start(largeMarker:true);Reach(large,p=>p.SkillPrompt?.SkillId==Xueyi);Require(large.Events.Select(e=>e.Payload).OfType<PlayerMarkerChangedEvent>().Any(e=>e.Marker==PlayerMarkerKind.Yi&&e.Delta==24),"Actual generic population multiplier grants24 without old fixed20 cap.");Cold(large,larger);
        var(non,nr)=Start(lord:false);Play(non);Require(Yi(non)==0&&!non.Events.Select(e=>e.Payload).OfType<PlayerMarkerChangedEvent>().Any(e=>e.Marker==PlayerMarkerKind.Yi&&e.PlayerSeat==0),"Actual nonlord printed qualification cannot initialize blood markers.");Cold(non,nr);
        var(dup,dr)=Start();var owner=Players(dup)[0];var source=owner.SkillGrants.Grants.Single(x=>x.SkillId==Xueyi);owner.SkillGrants.Grant(source with{GrantId="host:duplicate",SkillInstanceId="host:duplicate",SourceId="host:duplicate"});Reach(dup,p=>p.SkillPrompt?.SkillId==Xueyi);Require(Yi(dup)==8,"HOST duplicate source before actual start cannot duplicate initial grant.");Skip(dup);Play(dup);Require(dup.Events.Select(e=>e.Payload).OfType<PlayerMarkerChangedEvent>().Count(e=>e.Marker==PlayerMarkerKind.Yi&&e.Delta>0)==1,"One grant across duplicate instance lifecycle.");
        var(frozen,fr)=Start(startPause:true);Reach(frozen,p=>p.SkillPrompt?.SkillId=="fixture:ys-start-pause");var window=frozen.ResolutionStack.OfType<ProgramLifecycleTriggerWindowFrame>().Single(x=>x.Window==SkillProgramTriggerWindow.GameStarting);Require(window.FrozenFactionPopulation!.GetValueOrDefault("qun")==4,"Real owning window freezes population before startup child.");Players(frozen)[1].ChosenFactionId="wei";Skip(frozen);Reach(frozen,p=>p.SkillPrompt?.SkillId==Xueyi);Require(Yi(frozen)==8,"HOST faction mutation inside actual earlier child cannot change frozen population.");Witness(frozen,"host-frozen-population");
    }
    public static void PlayCostExtraChildrenAndCold()
    {
        var(g,r)=Start(gain:true,extra:true);Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(g);Play(g);Require(Yi(g)==8,"Decline spends no marker in actual extra Play.");End(g);Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);var hand=g.State.Players[0].HandCount;Activate(g);Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:ys-gain");Require(Yi(g)==7&&g.State.Players[0].HandCount==hand+1,"Normal Play actual cost1 Draw1 opens real gain child.");Require(Limit(g)==g.State.Players[0].Hp+7,"Paid marker immediately reduces derived limit.");Cold(g,r);Witness(g,"paid-draw-child");Skip(g);Play(g);Require(Yi(g)==7&&g.State.Players[0].HandCount==hand+1,"Child resumes without paying or drawing twice.");Cold(g,r);
        var(lost,lr)=Start(gain:true);Reach(lost,p=>p.SkillPrompt?.SkillId==Xueyi);Activate(lost);Reach(lost,p=>p.SkillPrompt?.SkillId=="fixture:ys-gain");var oldHand=lost.State.Players[0].HandCount;var grant=Players(lost)[0].SkillGrants.Grants.Single(x=>x.SkillId==Xueyi);Players(lost)[0].SkillGrants.RemoveGrant(grant.GrantId);Skip(lost);Play(lost);Require(Yi(lost)==7&&lost.State.Players[0].HandCount==oldHand,"HOST source loss after real Draw preserves paid fact and cancels remaining binding without refund/reissue.");
        var(z,zr)=Start(zeroYi:true);Play(z);Require(Yi(z)==0&&!z.Events.Select(e=>e.Payload).OfType<ProgramBindingStartedEvent>().Any(e=>e.SkillId==Xueyi&&e.BindingId=="spend-yi-draw"),"Actual startup removal makes zero-marker Play offer unaffordable.");Cold(z,zr);
    }
    public static void ConversionAndActualRemainingTargets()
    {
        foreach(var physical in new[]{false,true})
        {
            var(g,r)=Start(kind:physical?"arrow_barrage":"crossbow");Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(g);Play(g);var oldHand=g.State.Players[0].HandCount;
            if(physical)Physical(g);else Convert(g,Luanji);
            Reach(g,p=>p.SkillPrompt?.SkillId==Luanji);Cold(g,r);Witness(g,"exclude-offer-"+physical);for(var seat=1;seat<g.PlayerCount;seat++)Require(g.CreateSnapshot(seat).PendingDecision==null,"Foreign viewers cannot see the exclusion chooser prompt.");Activate(g);var p=P(g)!;var before=GameCheckpointJson.Serialize(g.CreateCheckpoint());var rejected=g.Submit(new AnswerPromptCommand((p.PlayerSeat+1)%g.PlayerCount,p.PromptId,p.Choices[0].Id,g.Revision));Require(!rejected.Accepted&&before==GameCheckpointJson.Serialize(g.CreateCheckpoint()),"Foreign actor rejects atomically.");
            var choice=p.Choices.Last();var target=choice.Targets.Single();Answer(g,c=>c.Id==choice.Id);var use=g.ResolutionStack.OfType<CardUseFrame>().Single(x=>x.CardKind==CardKind.ArrowBarrage);
            Require(use.ArrowBarrageExclusion?.TargetSeat==target&&!use.TargetSeats.Contains(target)&&use.TargetSeats.SequenceEqual(use.Action!.EffectiveDesignatedTargetSeats),"Actual selected target is removed from owning Use and effective Action, with scalar receipt.");
            Require(use.IneffectiveTargetSeats?.Contains(target)!=true,"Removed target is never mislabeled ineffective.");Require(g.Events.Select(e=>e.Payload).OfType<TargetsConfirmedEvent>().Any(e=>e.TargetSeats.Contains(target)),"Original confirmed historical fact keeps initial targets.");Cold(g,r);Witness(g,"excluded-"+physical);Activate(g);Witness(g,"later-observer-selection-"+physical);Require(P(g)!.Choices.All(c=>!c.Targets.Contains(target)),"Actual later finalized observer selects only current remaining targets.");SkipSelectionAndSettle(g);Require(g.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Count()==1,"One actual removal.");Require(g.State.Players[0].HandCount==oldHand-(physical?1:2)+1,"Real physical/conversion Hand costs pay once.");Cold(g,r);
            if(!physical)Require(g.Events.Select(e=>e.Payload).OfType<ProgramViewAsConvertedEvent>().Single().PhysicalCardIds.Count==2,"Two Hand conversion pays exact two real entities.");
        }
        var(other,or)=Start(otherConversion:true);Reach(other,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(other);Play(other);Convert(other,"fixture:ys-other-conversion");Reach(other,p=>p.SkillPrompt?.SkillId==Luanji);Activate(other);Answer(other,c=>c.Targets.Count==1);Settle(other);Require(other.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Count()==1,"Another conversion source still offers actual actor exclusion.");Cold(other,or);
        var(skip,sr)=Start(kind:"arrow_barrage");Reach(skip,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(skip);Play(skip);Physical(skip);Reach(skip,p=>p.SkillPrompt?.SkillId==Luanji);Skip(skip);Settle(skip);Require(!skip.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Any(),"Decline retains all actual targets.");Cold(skip,sr);
    }
    public static void DuplicateLifetimeAndProhibition()
    {
        var(g,r)=Start(kind:"arrow_barrage");Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(g);Play(g);var player=Players(g)[0];var grant=player.SkillGrants.Grants.Single(x=>x.SkillId==Luanji);player.SkillGrants.Grant(grant with{GrantId="host:other-luanji",SkillInstanceId="host:other-luanji",SourceId="host:other-luanji"});Physical(g);Reach(g,p=>p.SkillPrompt?.SkillId==Luanji);Activate(g);Answer(g,c=>c.Targets.Count==1);Settle(g);Require(g.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Count()==1,"HOST duplicate instances on actual Use share one exclusion scalar.");
        var(lost,lr)=Start(kind:"arrow_barrage");Reach(lost,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(lost);Play(lost);Physical(lost);Reach(lost,p=>p.SkillPrompt?.SkillId==Luanji);Activate(lost);var lostGrant=Players(lost)[0].SkillGrants.Grants.Single(x=>x.SkillId==Luanji);Players(lost)[0].SkillGrants.RemoveGrant(lostGrant.GrantId);Answer(lost,c=>c.Targets.Count==1);Settle(lost);Require(!lost.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Any(),"HOST source disappearance before removal keeps actual target set.");
        var(ban,br)=Start(kind:"arrow_barrage",ban:true);Reach(ban,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(ban);Play(ban);Require(!ban.GetHumanLegalActions().Any(a=>a.Kind==LegalActionKind.ArrowBarrage||a.ProgramSkillId==Luanji),"Real pre-issue Use prohibition remains effective despite post-issue exclusion capability.");Cold(ban,br);
        var(actor,ar)=Start(kind:"arrow_barrage");Reach(actor,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(actor);Play(actor);Physical(actor);Reach(actor,p=>p.SkillPrompt?.SkillId==Luanji);Activate(actor);Answer(actor,c=>c.Targets.Count==1);var actual=actor.ResolutionStack.OfType<CardUseFrame>().Single(x=>x.CardKind==CardKind.ArrowBarrage);var changed=actual with{SourceSeat=1,Action=new CardActionContext(actual.Action!.ActionId,actual.Action.ParentActionId,actual.Action.Type,1,actual.Action.ProviderSeat,actual.Action.RequesterSeat,actual.Action.ResponderSeat,actual.Action.OpponentSeat,actual.Action.EffectiveKind,actual.TargetSeats,actual.Action.PhysicalCards,actual.Action.ConversionChain,actual.TargetSeats,actual.Action.EffectiveSuit,actual.Action.EffectiveRank)};typeof(GameEngine).GetMethod("UpdateProgramRoleCardUse",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(actor,[changed,changed.Action!]);Require(changed.ArrowBarrageExclusion==actual.ArrowBarrageExclusion,"HOST legal actor rewrite preserves owning one-use receipt.");Settle(actor);Require(actor.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Count()==1,"HOST rewritten actual Use cannot remove a second target.");
    }
    public static void ZeroTargetsNativeAndCompatibility()
    {
        foreach(var converted in new[]{false,true})
        {
            var(g,r)=Start(kind:converted?"nullification":"arrow_barrage",singleTarget:true,jizhi:true);Reach(g,p=>p.SkillPrompt?.SkillId==Xueyi);Skip(g);Play(g);var initial=g.State.Players[0].HandCount;if(converted)Convert(g,Luanji);else Physical(g);Reach(g,p=>p.SkillPrompt?.SkillId==Luanji);Activate(g);Answer(g,c=>c.Targets.Count==1);var use=g.ResolutionStack.OfType<CardUseFrame>().Single(x=>x.CardKind==CardKind.ArrowBarrage);Require(use.TargetSeats.Count==0&&use.Action!.TargetSeats.Count==0,"Actual final target may be removed to zero.");Cold(g,r);Witness(g,"zero-targets-"+converted);if(converted){Skip(g);Reach(g,p=>p.Kind==DecisionKind.Nullification&&p.PlayerSeat==0);Cold(g,r);Witness(g,"zero-real-nullification-offer");var paid=P(g)!.Choices.First(c=>c.Cards.Count==1).Cards.Single();Answer(g,c=>c.Cards.SequenceEqual([paid]));Settle(g);Require(g.CardMovements.Count(m=>m.CardId==paid&&m.From==CardLocation.Hand(0)&&m.To==CardLocation.Processing)==1,"Actual zero-target Nullification entity pays once.");}else Settle(g);Require(!g.Events.Select(e=>e.Payload).OfType<DamageAppliedEvent>().Any(),"Zero-target Use has no response attack or damage.");Require(g.Events.Select(e=>e.Payload).OfType<CardUseFinishedEvent>().Count(e=>e.CardKind==CardKind.ArrowBarrage)==1,"Zero-target actual Use finitely completes once through typed parent.");Require(g.Events.Select(e=>e.Payload).OfType<ProgramBindingStartedEvent>().Any(e=>e.SkillId=="classic:jizhi"),"Zero-target actual Use retains real Jizhi.");Require(g.State.Players[0].HandCount>=initial-(converted?2:1),"Zero-target real Jizhi retains original paid cost.");Cold(g,r);Witness(g,"zero-finished-"+converted);
        }
        var(n,nr)=Start(native:true,kind:"arrow_barrage");for(var i=0;i<130&&n.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Count()==0;i++)Drive(n);Require(n.Events.Select(e=>e.Payload).OfType<ProgramArrowBarrageTargetRemovedEvent>().Any(),"Formal native optional AI makes an actual exclusion based on public ally harm.");Cold(n,nr);Witness(n,"formal-native-exclusion");
        var rules=Read("rules");var presentation=Read("presentation");foreach(var bad in new[]{rules.Replace("\"multiplier\": 2","\"multiplier\": -1"),rules.Replace("\"valueMarker\": \"yi\"","\"valueMarker\": null"),rules.Replace("currentArrowBarrageTargets","currentCardUseTargets"),rules.Replace("cardUseTargetsFinalized","cardUseBeforeTargetEffects")}){var rejected=false;try{SkillProgramCatalog.Load(bad,presentation);}catch(InvalidOperationException){rejected=true;}Require(rejected,"New population/exclusion/marker resources reject malformed contexts.");}
        var old=new CardUseFrame(1,0,1,CardKind.ArrowBarrage,[1]);Require(!JsonSerializer.Serialize(old).Contains("ArrowBarrageExclusion"),"Legacy nullable card-use shape stays absent.");var modifier=SkillProgramCatalog.Load(Read("rules"),presentation).Programs[Xueyi].Modifiers.Single();Require(modifier.QueryDependencies.SequenceEqual([SkillRuleQueryDependency.MarkerState]),"Owner marker numeric query declares exact dependency.");
    }
    static int Limit(GameEngine g)=>(int)typeof(GameEngine).GetMethod("GetHandLimit",BindingFlags.NonPublic|BindingFlags.Instance)!.Invoke(g,[Players(g)[0]])!;
    static int Yi(GameEngine g)=>g.CreateSnapshot(0).Players[0].Markers?.Where(m=>m.Kind==PlayerMarkerKind.Yi).Sum(m=>m.Count)??0;
    static PendingDecision? P(GameEngine g)=>g.PendingDecision??Enumerable.Range(0,g.PlayerCount).Select(s=>g.CreateSnapshot(s,true).PendingDecision).FirstOrDefault(p=>p!=null);
    static CharacterState[] Players(GameEngine g)=>((IReadOnlyList<CharacterState>)typeof(GameEngine).GetField("_players",BindingFlags.NonPublic|BindingFlags.Instance)!.GetValue(g)!).ToArray();
    static void Activate(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");
    static void Skip(GameEngine g)=>Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");
    static void Answer(GameEngine g,Func<PromptChoice,bool> predicate){var p=P(g)!;Accept(g,new AnswerPromptCommand(p.PlayerSeat,p.PromptId,p.Choices.First(predicate).Id,g.Revision));}
    static void Reach(GameEngine g,Func<PendingDecision,bool> goal){for(var i=0;i<160;i++){if(P(g)is{}p&&goal(p))return;Drive(g);}throw new InvalidOperationException("Missing actual boundary: "+P(g)?.Prompt);}
    static void Play(GameEngine g)=>Reach(g,p=>p.Kind==DecisionKind.PlayCard&&p.PlayerSeat==0);
    static void End(GameEngine g)=>Accept(g,new EndPlayPhaseCommand(0,g.Revision,P(g)!.PromptId));
    static void Drive(GameEngine g)
    {
        if(P(g)is{}p&&p.PlayerSeat==g.State.HumanSeat){if(p.Kind==DecisionKind.PlayCard)Accept(g,new EndPlayPhaseCommand(p.PlayerSeat,g.Revision,p.PromptId));else Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip"||c.Cards.Count==0);}
        else Accept(g,new AdvanceOneStepCommand(g.Revision));
    }
    static void Settle(GameEngine g){for(var i=0;i<160;i++){if(P(g)is{Kind:DecisionKind.PlayCard,PlayerSeat:0})return;Drive(g);}throw new InvalidOperationException("Use did not finitely return to actual Play.");}
    static void SkipSelectionAndSettle(GameEngine g){Answer(g,c=>c.Targets.Count==1);Settle(g);}
    static void Physical(GameEngine g){var action=g.GetHumanLegalActions().First(a=>a.Kind==LegalActionKind.ArrowBarrage);Accept(g,new PlayCardCommand(0,action.CardId!.Value,action.SelectableTargetSeats??[],g.Revision,P(g)!.PromptId));}
    static void Convert(GameEngine g,string skill){var ids=g.State.Players[0].Hand.Take(2).Select(c=>c.Id).ToArray();Accept(g,new UseProgramSkillCommand(0,skill,Conversion,ids,[],g.Revision,P(g)!.PromptId));}
    static void Accept(GameEngine g,GameCommand command)
    {
        var before=GameCheckpointJson.Serialize(g.CreateCheckpoint());try{var result=g.Submit(CommandJson.Deserialize(CommandJson.Serialize([command])).Single());Require(result.Accepted,result.Error?.Message??"Rejected actual command.");}
        catch(Exception ex){if(Environment.GetEnvironmentVariable("CARD_YS_EVIDENCE") is{Length:>0}path){var d=Path.Combine(path,"actual-exception-"+(++EvidenceSequence));Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint-before.json"),before);File.WriteAllText(Path.Combine(d,"attempt-command.json"),CommandJson.Serialize([command]));File.WriteAllText(Path.Combine(d,"trusted-observed-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));File.WriteAllText(Path.Combine(d,"exception.txt"),ex.ToString());}throw;}
    }
    static void Cold(GameEngine g,ContentRegistry r){var restored=GameReplay.Restore(GameCheckpointJson.Deserialize(GameCheckpointJson.Serialize(g.CreateCheckpoint())),r);Require(CommandJson.Serialize(restored.AcceptedCommands)==CommandJson.Serialize(g.AcceptedCommands),"Cold prefix retains exact accepted commands.");for(var s=0;s<g.PlayerCount;s++)Require(SnapshotJson.Serialize(restored.CreateSnapshot(s))==SnapshotJson.Serialize(g.CreateSnapshot(s)),"Every viewer's cold public/private projection matches.");Require(g.CreateCardZoneDiagnostics().Select(x=>x.CardId).Distinct().Count()==g.CreateCardZoneDiagnostics().Count,"Physical entities conserved.");}
    static void Witness(GameEngine g,string label){if(Environment.GetEnvironmentVariable("CARD_YS_EVIDENCE") is not{Length:>0}path)return;var d=Path.Combine(path,label);Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"checkpoint.json"),GameCheckpointJson.Serialize(g.CreateCheckpoint()));File.WriteAllText(Path.Combine(d,"trusted-stack.json"),JsonSerializer.Serialize(g.ResolutionStack));for(var s=0;s<Math.Min(g.PlayerCount,4);s++)File.WriteAllText(Path.Combine(d,"view-"+s+".json"),SnapshotJson.Serialize(g.CreateSnapshot(s)));}
    static void Require(bool condition,string message){if(!condition)throw new InvalidOperationException(message);}
    static string Read(string type){using var stream=typeof(StandardContentPackage).Assembly.GetManifestResourceStream("CardGame.Content.Standard.SkillPrograms.boundary-yuan-shao."+type+".json")!;using var reader=new StreamReader(stream);return reader.ReadToEnd();}
    static SkillProgram Load(string id,string body)=>SkillProgramCatalog.Load("{\"schemaVersion\":"+SkillProgramCatalog.RulesSchemaVersion+",\"skills\":[{\"id\":\""+id+"\",\"revision\":1,"+body+"}]}","{\"schemaVersion\":3,\"skills\":{\""+id+"\":{\"name\":\"fixture\",\"description\":\"fixture\"}}}").Programs[id];
    static (GameEngine,ContentRegistry) Start(int count=4,bool lord=true,bool startPause=false,bool gain=false,bool extra=false,bool zeroYi=false,string kind="crossbow",bool otherConversion=false,bool ban=false,bool singleTarget=false,bool jizhi=false,bool native=false,bool god=false,bool largeMarker=false)
    {var r=ContentRegistry.Build(new StandardContentPackage(),new Fixture(count,startPause,gain,extra,zeroYi,kind,otherConversion,ban,singleTarget,jizhi,native,lord,god,largeMarker));var g=GameEngine.CreateStandard(new GameOptions{Seed=31,PlayerCount=count,HumanSeat=native?3:0,HumanRole=lord?Role.Lord:Role.Rebel,ModeId="identity:classic-ys-check",UseInteractiveSetup=!native,UseInteractiveDiscard=false,AdvanceAfterHumanCommands=false,MaxTurns=4},r);Accept(g,new StartGameCommand());if(!native){Reach(g,p=>p.Kind==DecisionKind.SelectGeneral);Accept(g,new SelectGeneralCommand(0,lord?"fixture:ys-owner":P(g)!.Choices[0].Parameters["general-id"],g.Revision,P(g)!.PromptId));}return(g,r);}
    sealed class Fixture(int count,bool startPause,bool gain,bool extra,bool zeroYi,string kind,bool otherConversion,bool ban,bool singleTarget,bool jizhi,bool native,bool lord,bool god,bool largeMarker):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture-ys",new(1,0,0),[]);
        public void Register(IContentRegistryBuilder b)
        {
            try{typeof(StandardContentPackage).Assembly.GetType("CardGame.Content.Standard.BoundaryYuanShaoContent")!.GetMethod("Register",BindingFlags.NonPublic|BindingFlags.Static)!.Invoke(null,[b]);}catch(TargetInvocationException ex){throw new InvalidOperationException(ex.InnerException?.ToString(),ex.InnerException);}
            var extras=new List<string>{Xueyi};var classic=ContentRegistry.Build(new StandardContentPackage(),new StandardActiveSkillExpansionPackage(true),new StandardRescueSkillExpansionPackage(),new StandardClassicGeneralPackage());
            if(extra){b.AddSkill(classic.GetSkill("classic:dangxian"));extras.Add("classic:dangxian");}if(jizhi){b.AddSkill(classic.GetSkill("classic:jizhi"));extras.Add("classic:jizhi");}
            void Add(string id,string body,bool owner=true){b.AddSkill(new(id,id,"fixture"){Program=Load(id,body)});if(owner)extras.Add(id);}
            Add("fixture:ys-after-final","\"triggers\":[{\"id\":\"observe-remaining\",\"window\":\"cardUseTargetsFinalized\",\"ownerRelation\":\"actor\",\"cardKinds\":[\"arrowBarrage\"],\"priority\":-100,\"optional\":true,\"effects\":[{\"op\":\"selectTargets\",\"target\":\"owner\",\"targetKind\":\"currentCardUseTargets\",\"minimumTargets\":1,\"maximumTargets\":1,\"targetAiOrder\":\"cardEffectIntervention\"},{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]");
            if(singleTarget)Add("fixture:ys-after-zero","\"triggers\":[{\"id\":\"pause\",\"window\":\"cardUseTargetsFinalized\",\"ownerRelation\":\"actor\",\"cardKinds\":[\"arrowBarrage\"],\"priority\":-101,\"optional\":true,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]");
            if(largeMarker)Add("fixture:ys-large","\"triggers\":[{\"id\":\"grant-large\",\"window\":\"gameStarting\",\"subject\":\"owner\",\"optional\":false,\"priority\":100,\"effects\":[{\"op\":\"grantFactionPopulationMarker\",\"target\":\"owner\",\"factionId\":\"qun\",\"marker\":\"yi\",\"multiplier\":6}]}]");
            if(startPause)Add("fixture:ys-start-pause","\"triggers\":[{\"id\":\"pause\",\"window\":\"gameStarting\",\"subject\":\"owner\",\"priority\":100,\"optional\":true,\"effects\":[{\"op\":\"draw\",\"target\":\"owner\",\"amount\":1}]}]");
            if(gain)Add("fixture:ys-gain","\"triggers\":[{\"id\":\"pause\",\"window\":\"cardsGained\",\"subject\":\"owner\",\"destinationZones\":[\"hand\"],\"movementOccurrence\":\"perBatch\",\"optional\":true,\"effects\":[{\"op\":\"selectOwnedCards\",\"target\":\"owner\",\"zones\":[\"hand\"],\"amount\":1,\"resultBind\":\"selected\"},{\"op\":\"moveBoundCards\",\"target\":\"owner\",\"sourceBind\":\"selected\",\"destination\":\"discardPile\"}]}]");
            if(zeroYi)Add("fixture:ys-zero","\"triggers\":[{\"id\":\"remove\",\"window\":\"gameStarting\",\"subject\":\"owner\",\"priority\":-100,\"optional\":false,\"effects\":[{\"op\":\"changeParticipantMarker\",\"target\":\"owner\",\"marker\":\"yi\",\"amount\":-8}]}]");
            if(ban)Add("fixture:ys-ban","\"triggers\":[{\"id\":\"ban\",\"window\":\"playPhaseStarting\",\"subject\":\"owner\",\"optional\":false,\"priority\":100,\"effects\":[{\"op\":\"grantTurnCardActionProhibition\",\"target\":\"owner\",\"cardKinds\":[\"arrowBarrage\"],\"actionTypes\":[\"use\"]}]}]");
            if(otherConversion){var catalog=SkillProgramCatalog.Load(Read("rules").Replace(Luanji,"fixture:ys-other-conversion"),Read("presentation").Replace(Luanji,"fixture:ys-other-conversion"));b.AddSkill(new("fixture:ys-other-conversion","other","fixture"){Program=catalog.Programs["fixture:ys-other-conversion"]});extras.Add("fixture:ys-other-conversion");}
            if(singleTarget)Add("fixture:ys-shield","\"cardPolicies\":[{\"id\":\"avoid-arrow\",\"kind\":\"prohibitTarget\",\"cardKinds\":[\"arrowBarrage\"]}]",false);
            b.AddGeneral(new("fixture:ys-owner","主公","supporter",Luanji,god?"god":"qun",8,extras));
            for(var i=1;i<count;i++)b.AddGeneral(new("fixture:ys-target-"+i,"目标"+i,"supporter",native||!lord?Luanji:"standard:none",god&&i>1?"wei":"qun",8,!lord?[Xueyi]:singleTarget&&i>1?["fixture:ys-shield"]:[]));
            b.AddDeck(new("fixture:ys-deck","固定",4,0,[]){PhysicalCards=Enumerable.Range(0,count*30).Select(i=>new ContentDeckPhysicalCard("standard:"+kind,Suit.Spade,i%13+1)).ToArray()});
            b.AddMode(new("identity:classic-ys-check","固定",count,count,new Dictionary<string,int>{{nameof(Role.Lord),1},{nameof(Role.Loyalist),1},{nameof(Role.Rebel),count-2}},"fixture:ys-deck",GeneralCandidateCount:count,GeneralPoolIds:new[]{"fixture:ys-owner"}.Concat(Enumerable.Range(1,count-1).Select(i=>"fixture:ys-target-"+i)).ToArray()));
        }
    }
}
