using CardGame.Core;
using CardGame.Content.Standard;
using System.Reflection;
using System.Text.Json;
internal static class FengLinZuoCiChecks
{
    private const BindingFlags Flags=BindingFlags.Instance|BindingFlags.NonPublic;
    private static CharacterState Owner(GameEngine g)=>((IEnumerable<CharacterState>)typeof(GameEngine).GetField("_players",Flags)!.GetValue(g)!).First();
    private static IReadOnlyList<string> Enabled(GameEngine g)=>(IReadOnlyList<string>)typeof(GameEngine).GetMethod("EnabledContentSkillIds",Flags)!.Invoke(g,[Owner(g)])!;
    private static PrivateGeneralLibrarySnapshot Library(GameEngine g)=>g.CreateSnapshot(0).Players[0].PrivateGeneralLibraries!.Single();
    private static PendingDecision P(GameEngine g)=>g.PendingDecision??g.CreateSnapshot(0,true).PendingDecision!;
    private static void Require(bool b,string m){if(!b)throw new InvalidOperationException(m);}
    private static void Accept(GameEngine g,GameCommand c){var r=g.Submit(c);Require(r.Error is null,r.Error?.Message??"Rejected");}
    private static void Answer(GameEngine g,Func<PromptChoice,bool> pick){var p=P(g);var c=p.Choices.FirstOrDefault(pick)??throw new InvalidOperationException("No choice: "+JsonSerializer.Serialize(p));Accept(g,new AnswerPromptCommand(p.PlayerSeat,p.PromptId,c.Id,g.Revision));}
    private static void Reach(GameEngine g,Func<PendingDecision,bool> stop){for(var n=0;n<90;n++){var p=P(g);if(p is not null&&stop(p))return;if(p is {PlayerSeat:0,Kind:DecisionKind.PlayCard})Accept(g,new EndPlayPhaseCommand(0,g.Revision,p.PromptId));else if(p is {PlayerSeat:0})Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip"||c==p.Choices[0]);else Accept(g,new AdvanceOneStepCommand(g.Revision));}throw new InvalidOperationException("Missing boundary");}
    private static void Replay(GameEngine g,ContentRegistry r){var restored=GameReplay.Restore(GameCheckpointJson.Deserialize(GameCheckpointJson.Serialize(g.CreateCheckpoint())),r);string State(GameEngine x)=>JsonSerializer.Serialize(Enumerable.Range(0,4).Select(i=>x.CreateSnapshot(i)))+JsonSerializer.Serialize(x.ResolutionStack);Require(State(g)==State(restored),"Private libraries and owning selections replay at all four viewers.");}
    private static void Declare(GameEngine g,string skill){Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library");Answer(g,c=>c.Parameters.GetValueOrDefault("value")==skill);}
    public static void InitialPrivacyAndReplay()
    {
        var(g,r)=Start();Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));
        var library=Library(g);Require(library.Count==2&&library.GeneralIds!.Distinct().Count()==2,"Two unique initial avatars.");Require(!library.GeneralIds!.Contains("fixture:zc-owner"),"Living primary excluded.");Require(library.GeneralIds is IList<string> list&&list.IsReadOnly,"Owner private IDs frozen.");
        for(var i=1;i<4;i++){var view=g.CreateSnapshot(i);Require(view.Players[0].PrivateGeneralLibraries!.Single().GeneralIds is null,"Other viewers only count.");Require(view.PendingDecision is null||view.PendingDecision.Choices.Count==0,"Other viewer cannot inspect owner choices.");}
        Replay(g,r);Accept(g,new AdvanceOneStepCommand(g.Revision));Require(Library(g).Count==2&&g.Events.Count(e=>e.Payload is PrivateGeneralLibraryCountChangedEvent x&&x.Source.OwnerSeat==0)==1,"Paused resume cannot repay RNG.");
        Declare(g,"standard:wusheng");Require(Enabled(g).Contains("standard:wusheng"),"Structured view-as skill participates in actual binding.");Require(Owner(g).Gender==GeneralGender.Female&&g.CreateSnapshot(0).Players[0].FactionId=="wu","Gender/faction are true effective queries.");Replay(g,r);
    }
    public static void LayeredSuppressionAndLocalDisable()
    {
        // Fixed direct HP/grant fixture mutations; this method does not claim command replay.
        var(g,r)=Start();Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(g,"fixture:zc-suppression");var owner=Owner(g);var cap=owner.SkillGrants.Grants.Single(x=>x.SkillId=="classic:huashen");var borrowed=owner.SkillGrants.Grants.Single(x=>x.GeneralLibraryProjection is not null);Require(((IReadOnlyList<string>)typeof(GameEngine).GetMethod("AdvancedOwnedSkillIds",Flags)!.Invoke(g,[owner])!).Contains(borrowed.SkillId),"Qualified raw projection counts as advanced ownership.");
        owner.Hp=1;var rev=g.Revision;var events=g.Events.Count;var grants=owner.SkillGrants.Revision;for(var i=0;i<5;i++){Require(!Enabled(g).Contains("classic:huashen")&&!Enabled(g).Contains("fixture:zc-suppression"),"Base-live borrowed suppressor suppresses its source and final derived grant without oscillation.");Require(owner.Gender==GeneralGender.Male&&Library(g).Gender is null,"Suppressed attributes restore original.");}
        Require(g.Revision==rev&&g.Events.Count==events&&owner.SkillGrants.Revision==grants,"Repeated queries are observational.");owner.Hp=3;Require(Enabled(g).Contains("fixture:zc-suppression")&&owner.Gender==GeneralGender.Female,"HP recovery restores same retained source.");owner.SkillGrants.SetEnabled(cap.GrantId,false);Require(!Enabled(g).Contains("fixture:zc-suppression")&&owner.Gender==GeneralGender.Male,"Source local disable disables grant and attributes.");owner.SkillGrants.SetEnabled(cap.GrantId,true);owner.SkillGrants.SetEnabled(borrowed.GrantId,false);Require(!Enabled(g).Contains("fixture:zc-suppression"),"Derived local disable retained independently.");Require(!((IReadOnlyList<string>)typeof(GameEngine).GetMethod("AdvancedOwnedSkillIds",Flags)!.Invoke(g,[owner])!).Contains("fixture:zc-suppression"),"Disabled derived skill is not counted by advanced ownership.");owner.Hp=1;Require(Enabled(g).Contains("classic:huashen"),"Disabled borrowed suppressor is absent from stable input.");
    }
    public static void SameAvatarProgramAndActualEnd()
    {
        var(g,r)=Start();Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(g,"standard:wusheng");var avatar=Library(g).RevealedGeneralId;Reach(g,p=>p.PlayerSeat==0&&p.SkillPrompt?.SkillId=="classic:huashen"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Parameters.GetValueOrDefault("value")==avatar);Answer(g,c=>c.Parameters.GetValueOrDefault("value")=="fixture:zc-program");Require(Enabled(g).Contains("fixture:zc-program")&&!Enabled(g).Contains("standard:wusheng"),"Same avatar may select a native Program skill.");Replay(g,r);
        Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);Require(g.CreateSnapshot(0).Players[0].Hand.Count==7,"Borrowed Program executes its actual normal-draw child in addition to draw phase.");var ends=g.Events.Count(e=>e.Payload is TurnEndedEvent);Accept(g,new EndPlayPhaseCommand(0,g.Revision,P(g).PromptId));Reach(g,p=>p.PlayerSeat==0&&p.SkillPrompt?.SkillId=="classic:huashen"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Require(g.Events.Count(e=>e.Payload is TurnEndedEvent)>ends,"Replacement occurs after genuine TurnEnded, not Ending.");Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Parameters.GetValueOrDefault("value")==avatar);Answer(g,c=>c.Parameters.GetValueOrDefault("value")=="standard:wusheng");Replay(g,r);
    }
    public static void DamagePointsAndGlobalPool()
    {
        var(g,r)=Start();Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(g,"standard:wusheng");Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);Accept(g,new UseProgramSkillCommand(0,"fixture:zc-damage","hit",[],[],g.Revision,P(g).PromptId));for(var i=0;i<2;i++){Reach(g,p=>p.PlayerSeat==0&&p.SkillPrompt?.SkillId=="classic:xinsheng");Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");}Require(Library(g).Count==4&&Library(g).GeneralIds!.Distinct().Count()==4,"Two true damage points acquire one independent avatar each.");Replay(g,r);
        var(m,mr)=Start(multi:true);Reach(m,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(m,"standard:wusheng");Reach(m,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);var all=Enumerable.Range(0,4).SelectMany(i=>m.CreateSnapshot(i).Players[i].PrivateGeneralLibraries??[]).SelectMany(l=>l.GeneralIds??[]).ToArray();Require(all.Length==8&&all.Distinct().Count()==8,"Four owners hold a global nonduplicated pool.");Require(!all.Intersect(m.CreateSnapshot(0,true).Players.Select(p=>p.GeneralId)).Any(),"All living primaries excluded.");Replay(m,mr);
    }
    public static void GodFactionConversionAndSourceRemoval()
    {
        // Conversion/source mutation fixture deliberately does not claim those mutations replay.
        var(g,r)=Start(god:true);Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(g,"classic:zhenliang");Require(P(g).Choices.Any(c=>c.Parameters.GetValueOrDefault("value")=="wu"),"God declaration owns separate faction prompt.");Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("value")=="wu");Require(g.CreateSnapshot(0).Players[0].FactionId=="wu","Chosen avatar god faction applies.");var owner=Owner(g);owner.ChosenFactionId="wei";var state=typeof(GameEngine).GetField("_skillRuntimeState",Flags)!.GetValue(g)!;state.GetType().GetMethod("ToggleConversionState")!.Invoke(state,[0,"classic:zhenliang"]);var cap=owner.SkillGrants.Grants.Single(x=>x.SkillId=="classic:huashen");owner.SkillGrants.SetEnabled(cap.GrantId,false);Require(owner.Gender==GeneralGender.Male,"Disable restores gender.");Require((string?)typeof(GameEngine).GetMethod("GetEffectiveFactionId",Flags)!.Invoke(g,[owner])=="wei","Original chosen faction survives avatar override.");owner.SkillGrants.SetEnabled(cap.GrantId,true);Require((SkillPolarity)state.GetType().GetMethod("GetConversionState")!.Invoke(state,[0,"classic:zhenliang"])! ==SkillPolarity.Yin,"Recovery retains borrowed named conversion state.");owner.SkillGrants.RemoveGrant(cap.GrantId);typeof(GameEngine).GetMethod("SynchronizePrivateGeneralLibraries",Flags)!.Invoke(g,[]);Require(g.CreateSnapshot(0).Players[0].PrivateGeneralLibraries is null&&!owner.SkillGrants.Grants.Any(x=>x.GeneralLibraryProjection is not null),"Exact lost source cleans its library, projection, and attributes.");
    }
    public static void BorrowedLordProjectionSources()
    {
        // Direct disable/loss fixture mutations are mechanism checks, not command-replay evidence.
        var(g,r)=Start(weidi:true);Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library");Require(!P(g).Choices.Any(c=>c.Parameters.GetValueOrDefault("value") is "fixture:zc-limited" or "classic:hujia" or "classic:huangtian"),"Limited and Lord tags cannot be declared.");Answer(g,c=>c.Parameters.GetValueOrDefault("value")=="classic:weidi");Require(Enabled(g).Contains("classic:hujia")&&Enabled(g).Contains("classic:huangtian"),"Borrowed Weidi qualifies actual native response and contribution bindings.");Replay(g,r);var owner=Owner(g);var cap=owner.SkillGrants.Grants.Single(x=>x.SkillId=="classic:huashen");var hujia=owner.SkillGrants.Grants.Single(x=>x.LordProjection is not null&&x.SkillId=="classic:hujia");Require((bool)typeof(GameEngine).GetMethod("HasSkillRoleQualification",Flags)!.Invoke(g,[owner,hujia.SkillId,hujia.SkillInstanceId,Role.Lord])!,"Exact second-level binding has host eligibility.");var ids=owner.SkillGrants.Grants.Select(x=>x.GrantId).ToArray();var rev=owner.SkillGrants.Revision;var events=g.Events.Count;
        owner.SkillGrants.SetEnabled(cap.GrantId,false);rev++;for(var i=0;i<5;i++)Require(!Enabled(g).Contains("classic:hujia")&&!Enabled(g).Contains("classic:huangtian"),"Source disable invalidates both layers without recursive query.");Require(owner.SkillGrants.Revision==rev&&g.Events.Count==events&&ids.SequenceEqual(owner.SkillGrants.Grants.Select(x=>x.GrantId)),"Queries neither regrant nor remove retained relationships.");owner.SkillGrants.SetEnabled(cap.GrantId,true);Require(Enabled(g).Contains("classic:hujia"),"Both layers recover.");owner.SkillGrants.SetEnabled(hujia.GrantId,false);typeof(GameEngine).GetMethod("SynchronizeLordSkillProjections",Flags)!.Invoke(g,[]);Require(!Enabled(g).Contains("classic:hujia")&&Enabled(g).Contains("classic:huangtian"),"Second-level local disable retained independently.");owner.SkillGrants.RemoveGrant(cap.GrantId);typeof(GameEngine).GetMethod("SynchronizePrivateGeneralLibraries",Flags)!.Invoke(g,[]);Require(!Enabled(g).Contains("classic:huangtian")&&!owner.SkillGrants.Grants.Any(x=>x.LordProjection is not null||x.GeneralLibraryProjection is not null),"Exact source loss cleans both levels.");
    }
    public static void OldRegistryHasNoLibraryShape()
    {
        var(_,r)=Start();var old=ContentRegistry.Build(new WithoutLibrary(r));var g=GameEngine.CreateStandard(new GameOptions{Seed=17,PlayerCount=4,HumanSeat=0,HumanRole=Role.Lord,ModeId="identity:zc-fixture",UseInteractiveSetup=true,AdvanceAfterHumanCommands=false,UseInteractiveDiscard=false},old);Accept(g,new StartGameCommand());Accept(g,new SelectGeneralCommand(0,"fixture:zc-owner",g.Revision,P(g).PromptId));Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);Require(!g.Events.Any(e=>e.Payload is PrivateGeneralLibraryCountChangedEvent or PrivateGeneralLibraryDeclaredEvent),"No 1640 registry never captures new facts.");Require(!JsonSerializer.Serialize(g.CreateSnapshot(0)).Contains("PrivateGeneralLibraries"),"Null additive DTO omitted in old snapshot.");Replay(g,old);
    }
    public static void CurrentTurnSuppressionPreservesBorrowedLockedAudit()
    {
        // The library/declaration comes from real commands; suppression and exact
        // grant lifecycle mutations below are host audit, not replay evidence.
        var(g,r)=Start();Reach(g,p=>p.PlayerSeat==0&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="private-general-library"));Declare(g,"fixture:zc-suppression");
        Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);
        var owner=Owner(g);var cap=owner.SkillGrants.Grants.Single(x=>x.SkillId=="classic:huashen");
        var borrowed=owner.SkillGrants.Grants.Single(x=>x.GeneralLibraryProjection is not null);
        var players=((IEnumerable<CharacterState>)typeof(GameEngine).GetField("_players",Flags)!.GetValue(g)!).ToArray();
        players[1].SkillGrants.Grant(new("audit-source","fixture:zc-damage","audit-source","acquired:audit"));
        var f=new ProgramSkillFrame(90002,1,"fixture:zc-damage","hit",r.GetSkill("fixture:zc-damage").Program!.GameplayHash,1,[],[0]){SkillInstanceId="audit-source"};
        typeof(GameEngine).GetMethod("PushRuntimeFrame",Flags)!.Invoke(g,[f]);
        typeof(GameEngine).GetMethod("IssueCurrentTurnNonLockedSkillSuppression",Flags)!.Invoke(g,[f,0]);
        Require(!Enabled(g).Contains("classic:huashen")&&Enabled(g).Contains("fixture:zc-suppression"),"Current-turn suppression disables Huashen activation while preserving its already acquired Locked skill.");
        Require(owner.Gender==GeneralGender.Female&&g.CreateSnapshot(0).Players[0].FactionId=="wu","Already declared avatar identity survives temporary nonlocked suppression.");
        owner.SkillGrants.SetEnabled(cap.GrantId,false);Require(!Enabled(g).Contains("fixture:zc-suppression")&&owner.Gender==GeneralGender.Male,"True local source disable still suspends derived Locked skill and attributes.");
        owner.SkillGrants.SetEnabled(cap.GrantId,true);Require(Enabled(g).Contains("fixture:zc-suppression"),"Source local recovery restores acquired locked grant while turn fact remains.");
        owner.SkillGrants.SetEnabled(borrowed.GrantId,false);
        typeof(GameEngine).GetMethod("ExpireCurrentTurnNonLockedSkillSuppressions",Flags)!.Invoke(g,[g.CreateSnapshot(0).TurnNumber,0]);
        Require(Enabled(g).Contains("classic:huashen")&&!Enabled(g).Contains("fixture:zc-suppression"),"Actual expiry cannot unlock a locally disabled derived skill.");
        owner.SkillGrants.SetEnabled(borrowed.GrantId,true);owner.SkillGrants.RemoveGrant(cap.GrantId);
        typeof(GameEngine).GetMethod("SynchronizePrivateGeneralLibraries",Flags)!.Invoke(g,[]);
        Require(!Enabled(g).Contains("fixture:zc-suppression")&&owner.Gender==GeneralGender.Male,"True source loss still removes the acquired relation.");
    }
    private sealed class WithoutLibrary(ContentRegistry source):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture:zc-old",new Version(1,0,0),[]);
        public void Register(IContentRegistryBuilder b){foreach(var c in source.Cards.Values)b.AddCard(c);foreach(var s in source.Skills.Values)b.AddSkill(s.Id is "classic:huashen" or "classic:xinsheng"?s with{Program=null}:s);foreach(var g in source.Generals.Values)b.AddGeneral(g);foreach(var d in source.Decks.Values)b.AddDeck(d);foreach(var m in source.Modes.Values)b.AddMode(m);}
    }
    private static (GameEngine,ContentRegistry) Start(bool multi=false,bool god=false,bool weidi=false)
    {
        var r=ContentRegistry.Build(new StandardContentPackage(),new StandardActiveSkillExpansionPackage(true),new StandardRescueSkillExpansionPackage(),new StandardClassicGeneralPackage(),new Fixture(multi,god,weidi));var g=GameEngine.CreateStandard(new GameOptions{Seed=17,PlayerCount=4,HumanSeat=0,HumanRole=weidi?Role.Loyalist:Role.Lord,ModeId="identity:zc-fixture",UseInteractiveSetup=true,AdvanceAfterHumanCommands=false,UseInteractiveDiscard=false,MaxTurns=4},r);Accept(g,new StartGameCommand());Accept(g,new SelectGeneralCommand(0,"fixture:zc-owner",g.Revision,P(g).PromptId));return(g,r);
    }
    private sealed class Fixture(bool multi,bool god,bool weidi):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture:zc",new Version(1,0,0),[]);
        public void Register(IContentRegistryBuilder b)
        {
            var damage=SkillProgramCatalog.Load($$"""{"schemaVersion":{{SkillProgramCatalog.RulesSchemaVersion}},"skills":[{"id":"fixture:zc-damage","revision":1,"activations":[{"id":"hit","minCards":0,"maxCards":0,"minTargets":0,"maxTargets":0,"targetKind":"anyLiving","usesPerTurn":1,"effects":[{"op":"damage","target":"owner","amount":2}]}]}]}""","""{"schemaVersion":3,"skills":{"fixture:zc-damage":{"name":"受伤夹具","description":"两点伤害"}}}""");b.AddSkill(new("fixture:zc-damage","受伤夹具","真实两点伤害"){Program=damage.Programs["fixture:zc-damage"]});
            var catalog=SkillProgramCatalog.Load($$"""{"schemaVersion":{{SkillProgramCatalog.RulesSchemaVersion}},"skills":[{"id":"fixture:zc-program","revision":1,"triggers":[{"id":"draw","window":"drawPhaseStarting","subject":"owner","optional":false,"effects":[{"op":"draw","target":"owner","amount":1}]}]}]}""","""{"schemaVersion":3,"skills":{"fixture:zc-program":{"name":"原生摸牌夹具","description":"摸一张"}}}""");b.AddSkill(new("fixture:zc-program","原生摸牌夹具","摸一张"){Program=catalog.Programs["fixture:zc-program"]});b.AddSkill(new("fixture:zc-suppression","缠怨语义夹具","HP1压制其他技"){SuppressionRule=new(1),Tags=SkillTag.Locked});b.AddSkill(new("fixture:zc-limited","限定夹具","不能借"){Tags=SkillTag.Limited});
            var ids=new List<string>{"fixture:zc-owner"};b.AddGeneral(new("fixture:zc-owner","化身机制","supporter","classic:huashen","qun",3,["classic:xinsheng","fixture:zc-damage"],GeneralGender.Male));for(var i=0;i<11;i++){var id=$"fixture:zc-avatar-{i}";ids.Add(id);b.AddGeneral(new(id,"备用化身","supporter",multi?"classic:huashen":"standard:wusheng",god?"god":"wu",3,[..(multi?new[]{"standard:wusheng"}:Array.Empty<string>()),"fixture:zc-program","fixture:zc-suppression","fixture:zc-limited","classic:zhenliang",..(weidi?new[]{"classic:weidi","classic:hujia","classic:huangtian"}:Array.Empty<string>())],GeneralGender.Female));}
            b.AddDeck(new("fixture:zc-deck","固定红色牌",4,2,[]){PhysicalCards=Enumerable.Range(0,80).Select(i=>new ContentDeckPhysicalCard("standard:slash",Suit.Heart,i%13+1)).ToArray()});b.AddMode(new("identity:zc-fixture","测试",4,4,new Dictionary<string,int>{{nameof(Role.Lord),1},{nameof(Role.Loyalist),1},{nameof(Role.Rebel),2}},"fixture:zc-deck",GeneralCandidateCount:12,GeneralPoolIds:ids));
        }
    }
}
