using System.Text.Json;
using CardGame.Core;
using CardGame.Content.Standard;
internal static class FengLinZhouFeiChecks
{
    public static void DomainFirstAndEquipmentSequence()
    {
        var (g,r)=Start();Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");
        while(P(g)!.Choices.Any(c=>c.Cards.Count==1))Answer(g,c=>c.Cards.Count==1);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");
        Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");Require(g.Events.Select(e=>e.Payload).OfType<FirstGameDomainCrossingEvent>().Count()==1,"Arbitrary HE is one true outbound batch, not per entity.");Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");var before=g.CreateSnapshot(0,true).Players.Select(p=>p.HandCount).ToArray();Answer(g,c=>c.Targets.SequenceEqual([1]));Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:zf-draw");Replay(g,r);Answer(g,c=>true);Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal"));Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal");ReachPlay(g);
        Require(g.CreateSnapshot(0).Players[1].HandCount==before[1]+1,"First outbound performs real recipient draw.");
        End(g);Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:zf-gain");Require(g.CreateCardZoneDiagnostics().Any(z=>z.Location.Zone==CardZoneKind.PublicPersistentPile),"Non-equipment gain waits before remaining equipment.");Replay(g,r);Answer(g,c=>true);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="recipient"));var hp=g.CreateSnapshot(0).Players[1].Hp;Answer(g,c=>c.Targets.SequenceEqual([1]));
        for(var n=0;n<30&&P(g)?.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="equip")==true;n++){Replay(g,r);Answer(g,c=>c.Cards.Count==1);if(P(g) is null)Accept(g,new AdvanceOneStepCommand(g.Revision));}
        ReachPlay(g);Require(g.CreateSnapshot(0).Players[1].Hp==hp-1,"Actual equipment uses end with one true Hp loss.");
        var uses=g.Events.Select(e=>e.Payload).OfType<CardActionAcceptedEvent>().Select(e=>e.Action).Where(a=>a.ActorSeat==1&&EquipmentCatalog.IsEquipment(a.EffectiveKind)&&a.PhysicalCards.Any(c=>c.From.Zone==CardZoneKind.PublicPersistentPile)).ToArray();Require(uses.Length>1,"Remaining equipment is truly used from the exact source, not given into hand or directly equipped.");
        Require(g.CardMovements.Any(m=>m.Reason==CardMoveReasons.EquipmentReplace),"Multiple same-slot equipment performs real replacement.");Require(g.Events.Select(e=>e.Payload).OfType<FirstGameDomainCrossingEvent>().Count()==2,"One turn has independent first inbound/outbound; ordinary processing does not create more.");Replay(g,r);
    }
    public static void ZeroEquipmentDoesNotLoseHp()
    {
        foreach(var storeNonEquipment in new[]{false,true})
        {
            var(g,r)=Start();Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");
            if(storeNonEquipment){var nonEquip=g.CreateCardZoneDiagnostics().Where(z=>z.Location==CardLocation.Hand(0)&&!EquipmentCatalog.IsEquipment(z.CardKind)).Select(z=>z.CardId).ToHashSet();while(P(g)!.Choices.Any(c=>c.Cards.Count==1&&nonEquip.Contains(c.Cards[0])))Answer(g,c=>c.Cards.Count==1&&nonEquip.Contains(c.Cards[0]));}
            Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");ReachPlay(g);var hp=g.CreateSnapshot(0).Players.Select(x=>x.Hp).ToArray();End(g);Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);Require(!g.Events.Select(e=>e.Payload).OfType<ProgramSkillHpLostEvent>().Any(e=>e.SkillId=="classic:kongsheng"),"Empty/non-equipment only sequence has no actual use and no Hp payment.");Replay(g,r);
        }
    }
    public static void FirstDeclineAndPrivateInbound()
    {
        var(g,r)=Start();Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Cards.Count==1);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="skip");ReachPlay(g);Require(g.Events.Select(e=>e.Payload).OfType<FirstGameDomainCrossingEvent>().Count(e=>e.MovedOut)==1,"Declining consumes the actual outbound first occurrence.");End(g);
        // The stored fixed entity may be equipment: choose the recipient if needed;
        // either non-equipment gain or true equipment cost crosses the inbound domain.
        Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin"||p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="recipient"));
        if(P(g)!.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="recipient")){Answer(g,c=>c.Targets.SequenceEqual([1]));Answer(g,c=>c.Cards.Count==1);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");}
        Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Targets.SequenceEqual([1]));Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="discard"));var privateChoice=P(g)!;Require(privateChoice.IsPrivate,"Each participant owns a private discard decision.");Require(g.CreateSnapshot(1).PendingDecision?.Choices.Count is null or 0,"Other viewer cannot enumerate owner's private discard entities.");Replay(g,r);Answer(g,c=>c.Cards.Count==1);Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal"));Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal");Require(g.CardMovements.Count(m=>m.Reason.Value=="skill-program.game-domain.discard")==2,"Inbound pays each participant's own true HE discard exactly once.");
    }
    public static void EquipmentHpLossUsesDyingChain()
    {
        var(g,r)=Start(true);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");var equipment=g.CreateCardZoneDiagnostics().Where(z=>z.Location==CardLocation.Hand(0)&&EquipmentCatalog.IsEquipment(z.CardKind)).Select(z=>z.CardId).ToHashSet();Answer(g,c=>c.Cards.Count==1&&equipment.Contains(c.Cards[0]));Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");ReachPlay(g);End(g);Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="recipient"));Answer(g,c=>c.Targets.SequenceEqual([1]));Answer(g,c=>c.Cards.Count==1);Replay(g,r);
        for(var i=0;i<30&&!g.Events.Select(e=>e.Payload).OfType<PlayerDyingEvent>().Any(e=>e.VictimSeat==1);i++){if(P(g)is{PlayerSeat:0} dyingPrompt){var skip=dyingPrompt.Choices.FirstOrDefault(c=>c.Parameters.GetValueOrDefault("program-action")=="skip"||c.Parameters.GetValueOrDefault("domain-action")=="skip-heal");Answer(g,c=>skip is not null?c.Id==skip.Id:true);}else Accept(g,new AdvanceOneStepCommand(g.Revision));}
        Require(g.Events.Select(e=>e.Payload).OfType<PlayerDyingEvent>().Any(e=>e.VictimSeat==1),"Final actual-use Hp loss enters the genuine dying chain.");Require(g.Events.Select(e=>e.Payload).OfType<ProgramSkillHpLostEvent>().Count(e=>e.SkillId=="classic:kongsheng")==1,"Dying continuation cannot repay the final Hp cost.");Replay(g,r);
    }
    public static void CatalogOptInAndPreparedCollections()
    {
        var(g,r)=Start();Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Cards.Count==1);var saved=g.ResolutionStack.OfType<ProgramSkillFrame>().Last().PileEquipment!.SelectedIds;Require(saved is System.Collections.Generic.IList<int> list&&list.IsReadOnly,"New selected entities are read-only owning-frame collections.");Replay(g,r);
        var legacy=ContentRegistry.Build(new WithoutDomain(r));var old=GameEngine.CreateStandard(new GameOptions{Seed=17,PlayerCount=4,HumanSeat=0,HumanRole=Role.Lord,ModeId="identity:classic-zf-fixture",UseInteractiveSetup=true,UseInteractiveDiscard=false,AdvanceAfterHumanCommands=false,MaxTurns=6},legacy);Accept(old,new StartGameCommand());Accept(old,new SelectGeneralCommand(0,"fixture:zf-owner",old.Revision,P(old)!.PromptId));Reach(old,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(old,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(old,c=>c.Cards.Count==1);Answer(old,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");ReachPlay(old);Require(!old.Events.Select(e=>e.Payload).OfType<FirstGameDomainCrossingEvent>().Any(),"Custom registry without 1540 never captures new facts despite true outside movement.");Replay(old,legacy);
    }
    private sealed class WithoutDomain(ContentRegistry source):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture:zf-old",new Version(1,0,0),[]);
        public void Register(IContentRegistryBuilder b){foreach(var c in source.Cards.Values)b.AddCard(c);foreach(var s in source.Skills.Values)b.AddSkill(s.Id=="classic:liangyin"?new ContentSkillDefinition(s.Id,s.Name,s.Description):s);foreach(var g in source.Generals.Values)b.AddGeneral(g);foreach(var d in source.Decks.Values)b.AddDeck(d);foreach(var m in source.Modes.Values)b.AddMode(m);}
    }
    public static void CurrentSourceCountHealing()
    {
        var(g,r)=Start(true);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");for(var i=0;i<5;i++)Answer(g,c=>c.Cards.Count==1);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");Answer(g,c=>c.Targets.SequenceEqual([1]));Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:zf-draw");Answer(g,c=>true);Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal"));Require(P(g)!.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="heal"&&c.Targets.SequenceEqual([1])),"Healing reevaluates the recipient's completed real draw and current same-source pile X.");Replay(g,r);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="heal"&&c.Targets.SequenceEqual([1]));Require(g.CreateSnapshot(0).Players[1].Hp==2,"Eligible recipient receives true recovery after child gains.");
    }
    public static void IllegalEquipmentStaysInPile()
    {
        var(g,r)=Start(disabledEquipment:true);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");var equipment=g.CreateCardZoneDiagnostics().Where(z=>z.Location==CardLocation.Hand(0)&&EquipmentCatalog.IsEquipment(z.CardKind)).Select(z=>z.CardId).ToHashSet();Answer(g,c=>c.Cards.Count==1&&equipment.Contains(c.Cards[0]));Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");ReachPlay(g);End(g);Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);Require(g.CreateCardZoneDiagnostics().Any(z=>z.Location.Zone==CardZoneKind.PublicPersistentPile&&equipment.Contains(z.CardId)),"Equipment illegal for every living recipient stays in its original source.");Require(!g.Events.Select(e=>e.Payload).OfType<ProgramSkillHpLostEvent>().Any(e=>e.SkillId=="classic:kongsheng"),"All-illegal equipment has zero accepted uses and zero Hp loss.");Replay(g,r);
    }
    public static void SameSourceMultiplePilesFreezeAssociation()
    {
        // Deliberate direct grant/zone fixture setup: it is not a command-replay test.
        foreach(var pileAlreadyExists in new[]{true,false})
        {
            var(g,r)=Start(true);Reach(g,p=>p.SkillPrompt?.SkillId=="classic:kongsheng"&&p.Choices.Any(c=>c.Parameters.GetValueOrDefault("program-action")=="activate"));Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");for(var i=0;i<5;i++)Answer(g,c=>c.Cards.Count==1);Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="store-finish");Reach(g,p=>p.SkillPrompt?.SkillId=="classic:liangyin");
            var flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;
            var owner=((IEnumerable<CharacterState>)typeof(GameEngine).GetField("_players",flags)!.GetValue(g)!).Single(p=>p.Seat==0);
            var stockInstance=owner.SkillGrants.Grants.Single(x=>x.SkillId=="classic:kongsheng").SkillInstanceId;
            owner.SkillGrants.Grant(new("fixture:zf-b","classic:kongsheng","fixture:zf-b",CharacterState.PrimarySkillSource));owner.SkillGrants.Grant(new("fixture:zf-a","classic:kongsheng","fixture:zf-a",CharacterState.PrimarySkillSource));
            PublicPersistentPileSource CreatePile(string instance)
            {var frame=new ProgramSkillFrame(999,0,"classic:kongsheng","store",r.Skills["classic:kongsheng"].Program!.GameplayHash,1,[],[]){SkillInstanceId=instance};return (PublicPersistentPileSource)typeof(GameEngine).GetMethod("EnsurePublicPileSource",flags)!.Invoke(g,[frame,int.MaxValue])!;}
            var stock=CreatePile(stockInstance);var stockIds=g.CreateCardZoneDiagnostics().Where(c=>c.Location==stock.Location).Select(c=>c.CardId).ToArray();
            var zones=typeof(GameEngine).GetField("_cardZones",flags)!.GetValue(g)!;void Move(int id,CardLocation from,CardLocation to)=>zones.GetType().GetMethod("Move")!.Invoke(zones,[id,from,to]);
            var b=CreatePile("fixture:zf-b");foreach(var card in g.CreateSnapshot(0).Players[0].Hand.Take(2))Move(card.Id,CardLocation.Hand(0),b.Location);
            PublicPersistentPileSource? a=null;if(pileAlreadyExists){a=CreatePile("fixture:zf-a");foreach(var id in stockIds)Move(id,stock.Location,a.Location);}
            Answer(g,c=>c.Parameters.GetValueOrDefault("program-action")=="activate");var draft=g.ResolutionStack.OfType<ProgramSkillFrame>().Last().DomainCrossing!;Require(draft.ReferenceSkillInstanceId=="fixture:zf-a","Same-source association is stable ordinal instance order, independent of insertion and pile existence.");Require((draft.ReferencePileLocation is not null)==pileAlreadyExists,"Known exact location is frozen; missing pile keeps an exact future instance.");
            if(a is null){a=CreatePile("fixture:zf-a");foreach(var id in stockIds)Move(id,stock.Location,a.Location);}
            // A newly earlier same-source grant must not replace an already frozen association.
            owner.SkillGrants.Grant(new("fixture:zf-0","classic:kongsheng","fixture:zf-0",CharacterState.PrimarySkillSource));var earlier=CreatePile("fixture:zf-0");var spare=g.CreateSnapshot(0).Players[0].Hand.First();Move(spare.Id,CardLocation.Hand(0),earlier.Location);
            var exactFrame=new ProgramSkillFrame(998,0,"classic:kongsheng","store",r.Skills["classic:kongsheng"].Program!.GameplayHash,1,[],[]){SkillInstanceId="fixture:zf-b"};var exact=((string?,CardLocation?))typeof(GameEngine).GetMethod("SelectDomainReference",flags)!.Invoke(g,[exactFrame,"classic:kongsheng"])!;Require(exact.Item1=="fixture:zf-b","Exact matching instance precedes lexical same-source alternatives.");
            Answer(g,c=>c.Targets.SequenceEqual([1]));Reach(g,p=>p.SkillPrompt?.SkillId=="fixture:zf-draw");Answer(g,c=>true);Reach(g,p=>p.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="skip-heal"));Require(P(g)!.Choices.Any(c=>c.Parameters.GetValueOrDefault("domain-action")=="heal"&&c.Targets.SequenceEqual([1])),"After complete children X is the frozen a pile's current five, not b/earlier/total; no multi-pile exception.");Answer(g,c=>c.Parameters.GetValueOrDefault("domain-action")=="heal"&&c.Targets.SequenceEqual([1]));Require(g.CreateSnapshot(0).Players[1].Hp==2,"Exact frozen association produces true recovery.");
        }
    }
    private static PendingDecision? P(GameEngine g)=>g.PendingDecision??Enumerable.Range(0,4).Select(i=>g.CreateSnapshot(i,true).PendingDecision).FirstOrDefault(p=>p is not null);
    private static void Require(bool b,string m){if(!b)throw new InvalidOperationException(m);}
    private static void Accept(GameEngine g,GameCommand c){var result=g.Submit(c);Require(result.Error is null,result.Error?.Message??"Rejected");}
    private static void Answer(GameEngine g,Func<PromptChoice,bool> pick){var p=P(g)!;Accept(g,new AnswerPromptCommand(p.PlayerSeat,p.PromptId,(p.Choices.FirstOrDefault(pick)??throw new InvalidOperationException("No fixture answer: "+JsonSerializer.Serialize(p))).Id,g.Revision));}
    private static void End(GameEngine g)=>Accept(g,new EndPlayPhaseCommand(0,g.Revision,P(g)!.PromptId));
    private static void ReachPlay(GameEngine g)=>Reach(g,p=>p.PlayerSeat==0&&p.Kind==DecisionKind.PlayCard);
    private static void Reach(GameEngine g,Func<PendingDecision,bool> stop)
    {for(var n=0;n<100;n++){if(P(g)is{}p&&stop(p))return;if(P(g)is{PlayerSeat:0,Kind:DecisionKind.PlayCard})End(g);else if(P(g)is{PlayerSeat:0} q){var skip=q.Choices.FirstOrDefault(c=>c.Parameters.GetValueOrDefault("program-action")=="skip"||c.Parameters.GetValueOrDefault("domain-action")=="skip-heal");Answer(g,c=>skip is not null?c.Id==skip.Id:c.Cards.Count==0);}else Accept(g,new AdvanceOneStepCommand(g.Revision));}throw new InvalidOperationException("Missing fixed boundary: "+JsonSerializer.Serialize(P(g)));}
    private static void Replay(GameEngine g,ContentRegistry r){var restored=GameReplay.Restore(GameCheckpointJson.Deserialize(GameCheckpointJson.Serialize(g.CreateCheckpoint())),r);string State(GameEngine x)=>JsonSerializer.Serialize(Enumerable.Range(0,4).Select(i=>x.CreateSnapshot(i,true)))+JsonSerializer.Serialize(x.ResolutionStack)+JsonSerializer.Serialize(x.CreateCardZoneDiagnostics());Require(State(g)==State(restored),"Four viewer/private and typed frame checkpoints replay exactly.");Require(g.CreateCardZoneDiagnostics().Count==80,"All entities conserved.");}
    private static (GameEngine,ContentRegistry) Start(bool fragileRecipient=false,bool disabledEquipment=false)
    {
        var r=ContentRegistry.Build(new StandardContentPackage(),new StandardActiveSkillExpansionPackage(true),new StandardRescueSkillExpansionPackage(),new StandardClassicGeneralPackage(),new Fixture(fragileRecipient,disabledEquipment));var g=GameEngine.CreateStandard(new GameOptions{Seed=17,PlayerCount=4,HumanSeat=0,HumanRole=Role.Lord,ModeId="identity:classic-zf-fixture",UseInteractiveSetup=true,UseInteractiveDiscard=false,AdvanceAfterHumanCommands=false,MaxTurns=6},r);Accept(g,new StartGameCommand());Accept(g,new SelectGeneralCommand(0,"fixture:zf-owner",g.Revision,P(g)!.PromptId));return(g,r);
    }
    private sealed class Fixture(bool fragileRecipient=false,bool disabledEquipment=false):IGameContentPackage
    {
        public PackageManifest Manifest{get;}=new("fixture:zf",new Version(1,0,0),[]);
        public void Register(IContentRegistryBuilder b)
        {
            var c=SkillProgramCatalog.Load($$"""{"schemaVersion":{{SkillProgramCatalog.RulesSchemaVersion}},"skills":[{"id":"fixture:zf-start","revision":1,"triggers":[{"id":"start","window":"gameStarting","subject":"owner","optional":false,"effects":[{"op":"draw","target":"owner","amount":8},{"op":"awaitOwnedCardMovement","target":"owner"}]}]},{"id":"fixture:zf-draw","revision":1,"triggers":[{"id":"gain","window":"cardsGained","subject":"owner","destinationZones":["hand"],"movementReasons":["skill-program.game-domain.draw"],"movementOccurrence":"perBatch","optional":false,"effects":[{"op":"chooseOption","target":"owner","resultBind":"resume","options":[{"id":"continue"}]}]}]},{"id":"fixture:zf-gain","revision":1,"triggers":[{"id":"gain","window":"cardsGained","subject":"owner","destinationZones":["hand"],"movementReasons":["skill-program.public-pile.non-equipment-gain"],"movementOccurrence":"perBatch","optional":false,"effects":[{"op":"chooseOption","target":"owner","resultBind":"resume","options":[{"id":"continue"}]}]}]}]}""","""{"schemaVersion":3,"skills":{"fixture:zf-start":{"name":"开局供牌","description":"真实摸牌"},"fixture:zf-draw":{"name":"良姻摸牌子链","description":"等待","optionLabels":{"continue":"继续"}},"fixture:zf-gain":{"name":"非装备获得子链","description":"等待","optionLabels":{"continue":"继续"}}}}""");foreach(var item in c.Programs)b.AddSkill(new(item.Key,item.Key,item.Key){Program=item.Value});
            var slots=SkillProgramCatalog.Load($$"""{"schemaVersion":{{SkillProgramCatalog.RulesSchemaVersion}},"skills":[{"id":"fixture:zf-slots","revision":1,"triggers":[{"id":"disable","window":"gameStarting","subject":"owner","optional":false,"effects":[{"op":"alterEquipmentSlots","target":"owner","equipmentSlots":["weapon","armor","offensiveHorse","defensiveHorse","treasure"],"amount":0}]}]}]}""","""{"schemaVersion":3,"skills":{"fixture:zf-slots":{"name":"无装备栏夹具","description":"全禁装备栏"}}}""");foreach(var item in slots.Programs)b.AddSkill(new(item.Key,item.Key,item.Key){Program=item.Value});
            b.AddGeneral(new("fixture:zf-owner","周妃机制","supporter","classic:kongsheng","wu",20,disabledEquipment?["classic:liangyin","fixture:zf-start","fixture:zf-draw","fixture:zf-gain","fixture:zf-slots"]:["classic:liangyin","fixture:zf-start","fixture:zf-draw","fixture:zf-gain"]));for(var i=1;i<4;i++)b.AddGeneral(new($"fixture:zf-target-{i}","目标","supporter",disabledEquipment?"fixture:zf-slots":"standard:none","wu",20){InitialHp=fragileRecipient?1:null});
            b.AddDeck(new("fixture:zf-deck","固定实体",4,2,[]){PhysicalCards=Enumerable.Range(0,80).Select(i=>new ContentDeckPhysicalCard(i%3==0?"standard:crossbow":i%3==1?"standard:bagua":"standard:slash",i%2==0?Suit.Spade:Suit.Club,i%13+1)).ToArray()});b.AddMode(new("identity:classic-zf-fixture","测试",4,4,new Dictionary<string,int>{{nameof(Role.Lord),1},{nameof(Role.Loyalist),1},{nameof(Role.Rebel),2}},"fixture:zf-deck",GeneralCandidateCount:4,GeneralPoolIds:["fixture:zf-owner","fixture:zf-target-1","fixture:zf-target-2","fixture:zf-target-3"]));
        }
    }
}
