@{
    # Routine checks use existing name filters; each runner executes their union once.
    # Full validation retains every registration, including individual content scenarios.
    Core = @(
        'command', 'observer', 'viewer', 'prepared snapshot', 'internal failure',
        'skill program', 'lifecycle programs', 'shared post-event', 'Phase hand extra turn',
        'Actual draw obligation', 'Owned damage point judgment',
        'Prevented damage draw', 'Black trick target policy', 'Dying skill qualification', 'Nearest legal Slash',
        'Actual turn target commitment', 'Applied damage occurrence', 'Applied damage benefit',
        'Dual private color commitments', 'Damage judgment suit payment four suits',
        'shared use lifecycle', 'shared card-use', 'card movement', 'card inventory',
        'initial deal', 'invalid single and batch', 'draw and recover',
        'execution plans', 'skill executor', 'program gameplay hashes',
        'physical deck recipes', 'structured skill metadata', 'content registry',
        'standard package', 'composition kernel', 'rule query', 'slash resolution',
        'dying response', 'Xingshang', 'response use completion', 'selected gift',
        'configured active sequences', 'standard active programs', 'owned-card set',
        'turn card-use effects', 'active Program contracts', 'hand guidance',
        'actual marker payment', 'replacement draw and dying payment', 'two dynamic actual ends',
        'ordered nested native owner', 'payment nested comparison', 'first target history',
        'program conversion polarity shared state and replay',
        'Feng Lin Lu Zhi actual discard entry boundaries',
        'Ending child gift joins current boundary',
        'Feng Lin Yuan Shu command loss regrant source suppression',
        'Feng Lin Yuan Shu qualified awakening persistent local loss',
        'Feng Lin Zhou Fei first domains and true equipment sequence',
        'Feng Lin Zhou Fei same-source association freeze',
        'Feng Lin Congjian Equipment gift nested replay',
        'after turn ended return movement prelude ordering',
        'after turn ended due before window nested replay',
        'Feng Lin Zuo Ci initial privacy and replay',
        'Feng Lin Zuo Ci layered suppression and local disable',
        'Feng Lin Zuo Ci same avatar program and actual end',
        'Feng Lin Yu Ji',
        'boundary Lu Meng all table printed suits replay',
        'boundary Lu Meng cross owner skip chain resume death',
        'boundary Lu Meng Qinxue windows shared usage',
        'boundary Lu Meng opt in usage legacy shape',
        'Boundary Huang Gai actual provider color',
        'Boundary Huang Gai multi card color source lifecycle',
        'boundary Lu Xun actual trick hold lianying and return',
        'boundary Lu Xun HE payment exact Hand batch count',
        'boundary Liu Bei virtual Peach HP child',
        'boundary Liu Bei native provided use decline once',
        'boundary Liu Bei gift threshold recipient',
        'boundary Da Qiao atomic mixed discard replay',
        'boundary Hua Tuo ordered actual discard effective suit receipts',
        'participant discard mandatory cost cancellation preserves legal composition',
        'current turn nonlocked suppression host lifecycle audit',
        'boundary Guan Yu actual Played and black Hand rejection',
        'Boundary Zhang Fei actual recovery receipt limited child',
        'boundary Ma Chao Tieqi Paoxiao exact cancellation integration',
        'boundary Xiahou Dun real phases skip quota expiry',
        'boundary Xiahou Dun receipt before gain child source audit',
        'Exact top count partition normal draw',
        'Bound draw receipt per point nested gain',
        'boundary Zhen Ji exact receipt stop red discard',
        'boundary Zhen Ji receipt before child source loss',
        'Unconverted Trick draw receipt disposition',
        'Foreign equipment discard program selections',
        'Population reorder actual partition and short pile',
        'Population reorder real Ending Extra Scheduled',
        'HP pair freezes after payment children before draw children',
        'Equipment placement slot self equal boundaries',
        'Final target Slash frozen comparisons actual paid Dodge',
        'Paid HP loss rescue and gain children',
        'Paid HP loss source and legacy',
        'Boundary Deng Ai own turn slash discard judges authority',
        'Boundary Deng Ai awakening grants snatch and extra turn',
        'Boundary Jiang Wei declined taunt discards target card',
        'Boundary Jiang Wei dodged slash still discards',
        'Boundary Jiang Wei taunt runs twice per phase',
        'Boundary Jiang Wei awakening wakes once across phases',
        'Boundary Sun Ce own duel and red slash draw',
        'Boundary Sun Ce reclaim once per turn',
        'Boundary Sun Ce hunzi wakes draws and stays silent',
        'Boundary Sun Ce zhiba declined claim discards both'
        'Boundary Zhu Rong juxiang immunity claims resolved barbarian',
        'Boundary Zhu Rong winning pindian takes target card',
        'Boundary Zhu Rong lost pindian takes nothing',
        'Boundary Zhu Rong unlimited slash damage draws at phase end',
        'Boundary Zhu Rong dodged slash skips phase end draw',
        'Boundary Zhu Rong changbiao runs once per phase',
        'Boundary Meng Huo definitions and metadata',
        'Boundary Meng Huo barbarian immunity and attribution',
        'Boundary Meng Huo zaiqi asks chosen participants in order',
        'Boundary Meng Huo zaiqi draw only at full owner',
        'Boundary Meng Huo zaiqi decline leaves everyone alone',
        'Boundary Meng Huo zaiqi stays silent without red discards',,
        'Boundary Guan Xing Zhang Bao converted slash response follows pair color',
        'Boundary Guan Xing Zhang Bao turn skills expire with the turn'
        'Damage target mount paid children source lifetime',
        'Damage appearance Draw definitions physical colors cardless legacy',
        'Selected actor Duel actual Use and Nullification',
        'Damage target obtain nested Duel native cold',
        'Boundary Yuan Shao population start role marker limit',
        'Boundary Yuan Shao conversion actual remaining targets'
        'Recovery replacement Silver Lion Zhiheng HP and reward children',
        'Recovery replacement paid equipment tail',
        'Recovery replacement faction request Silver Lion cost before providers',
        'Program Iron Chain third target owned recast',
        'Equipment recast Silver Lion recovery and movement children',
        'BoundaryXuShu fixed target real Slash',
        'BoundaryXuShu declared deck criterion'
        'Character turned over Shebian both directions',
        'Character turned over Shebian occupied equipment slot',
        'Character turned over actual damage cursor',
        'Capped hand refresh',
        'HP paid shield',
        'Random Pindian',
        'Maximum Slash Pindian',
        'Bound card recast dynamic Slash',
        'Bound card recast Silver Lion',
        'Turn kind hand exemption',
        'Signed Slash modifier',
        'Bound discard Slash frozen suit',
        'Bound discard Slash equipment',
        'First round limited refund exact',
        'Current Slash entity claim basic',
        'Current Slash entity claim nonbasic',
        'Participant hand declined private take',
        'Participant hand mixed HE gift',
        'Participant hand per point effective red',
        'Participant hand program bound alcohol',
        'Next-use rank bonus',
        'Other dying recovery equipment',
        'Alternative phase cost actual',
        'Alternative phase cost equipped',
        'Ending hand count history',
        'Random reveal color Fire Attack',
        'Unrespondable counterspell equipment',
        'Discarded provenance virtual Alcohol',
        'Discarded provenance exact discard judgment',
        'Discarded provenance real turn all materials',
        'Actual turn use kinds independent hand suits',
        'Actual turn use kinds per Play draw'
    )
    Wpf = @(
        'original card artwork', 'overlapping hand', 'composed skills', 'conversion choices',
        'response context', 'hand responses', 'opaque target-card',
        'playback batches', 'saved UI boundaries', 'failed writes', 'public markers',
        'deferred hand alignment', 'Program conversion polarity stays visible',
        'declaration and general library views protect private faces',
        'Program paid choices',
        'Program exact top count restores private shared order',
        'Program population count private faces restore shared free order'
        'Program Iron Chain guide follows actual target count'
    )
}
