@{
    # Routine checks use existing name filters; each runner executes their union once.
    # Full validation retains every registration, including individual content scenarios.
    Core = @(
        'identity role general candidates', 'identity general variants', 'identity Rebel kill reward',
        'Chained state basic:',
        'Foreign selected card Slash:',
        'Paired color responses:',
        'Actor hand limit penalty:',
        'Play phase temporary skills:',
        'Round gained source uses:',
        'Unique maximum trick targets:',
        'Damage counterpart acquisition:',
        'Last zone conversions:',
        'Overflow target cancellation:',
        'Matching recast:',
        'Ordered printed skill loss:',
        'Recipient category mark:',
        'Off-turn used card gift:',
        'Turn default allocation:',
        'Round distinct basic use:',
        'Card response completion cost:',
        'Card response completion:',
        'Same name hand demand:',
        'Completed undamaged target reveal:',
        'Paired hand recast:',
        'Original hand entities:',
        'Outside phase draw discard:',
        'Native discard classification:',
        'Phase name prediction:',
        'Last damage source reciprocity:',
        'Category discard refund:',
        'Activation-count awakening:',
        'Unexpected Assault:',
        'Draw-funded distinct basic:',
        'Multiple original materials already moved and empty virtual responses',
        'Liejie source discard:',
        'Choice target prerequisite:',
        'Different color judgment replacement:',
        'Ending damage marker:',
        'Tongxie use provenance:',
        'Tang Ji paid continuation:',
        'Liu Hong activation:',
        'Draw advice and designated extra target:',
        'Gifted Slash hand policy:',
        'Public pile cash out:',
        'Current turn hand exchange:',
        'Exact owned card count and named targets:',
        'Actual target prompt retains the AI-owned attack',
        'Owned hand exact rank sum actual gift and recovery return',
        'Owned hand exact rank sum no solution and native AI',
        'Initial hand modifiers: owner maximum HP controls the real deal and dynamic hand limit',
        'Owner dying awakening paid HP tail returns once',
        'Owner dying replacement permanent source and optional ending replay',
        'Virtual ordinary trick composition frozen branches and public AI',
        'Ending Pindian win loss tie actual virtual tricks and cold return',
        'Trick target arbitrary hand gift empty Dismantlement and true counterspell',
        'Delayed trick target hand gift waits exact movement child',
        'Ending virtual trick real adjusted target sequence returns once',
        'Actual turn use ordinal:',
        'Actual second use foreign grants share state and expire on end',
        'Actual legacy Wine',
        'foreign ending owner and equipment costs wait once',
        'shared actual target loader keeps operation ownership',
        'public equipment half count draw resumes once',
        'Short range Slash and directed ending debt:',
        'Equipment Slash ownership:',
        'Actual hand gains and category gifts:',
        'Delegated judgment and gain gifts:', 'JudgedRankSlashPolicy.', 'skill program public pile preparation',
        'Phase hand seizure:', 'RecipientContestConsequences',
        'command', 'observer', 'viewer', 'prepared snapshot', 'internal failure',
        'declaration payment lookups', 'empty binding queries',
        'ordinary card snapshot reuse', 'skill runtime usage',
        'program state projection', 'public pile projection', 'zero material uses', 'legacy and borrowed sword zero material continuations',
        'damage cursor typed observers',
        'round-start programs include foreign owners and cold returns',
        'skill program', 'lifecycle programs', 'shared post-event', 'Phase hand extra turn',
        'Actual draw obligation', 'Owned damage point judgment',
        'Prevented damage draw', 'Black trick target policy', 'Dying skill qualification', 'Nearest legal Slash',
        'Actual turn target commitment', 'Applied damage occurrence', 'Applied damage benefit',
        'Dual private color commitments', 'Damage judgment suit payment four suits',
        'Granted entity extra phase distance', 'Frozen faction recovery game damage',
        'Next actual-use paid wins',
        'Original target addition rights', 'Foreign turn Wine actual actor',
        'Neighbor discard own first previous',
        'boundary cheng pu completion payment',
        'boundary wu guo tai paid equipment pair',
        'Paid actual target HP and original use return',
        'boundary li ru sequential discard top cost',
        'Whole equipment donation actual X and recovery',
        'boundary xiao qiao suit prevention equipment cost',
        'boundary lu su extra draw half hand gift',
        'Real color payment Duel back-damage and mandatory Ending claim',
        'boundary two zhangs equipment replacement',
        'boundary bu lian shi ordered opaque pair gift',
        'Foreign actual turn contest decline win expiry',
        'boundary ma dai shown color hand ban',
        'Ending pair two draws own extra round and cold',
        'Preparation discard actual cost',
        'Ordinary SP Cao Ren private whole hand',
        'Ordinary SP Pang De two real costs',
        'Ordinary Chen Lin deferred private offer next actual start exchange',
        'Ordinary SP Cai Wen Ji original Dying four suits private cost cold replay',
        'Ordinary Guan Yin Ping red equipment cost before lost HP targets and real fire draw',
        'ordinary OL Zhuge Ke empty-hand Dodge private top request and once payment',
        'Yang Xiu multi-target trick',
        'SP Ma Chao HP ordered distance and lost HP extra targets pay each target once',
        'Ordinary Fu Wan same-use benefit',
        'Ordinary Cao Hong real placement',
        'Ordinary Liu Xie Tianming SilverLion cost and unique current HP peer',
        'OL signed damage actual material',
        'Tiered Round true uses physical conversion and private cold',
        'Tiered Round shared quota and zero ordinary child',
        'Same actual use aid extra duel physical slash targets',
        'shared use lifecycle', 'shared card-use', 'card movement', 'card inventory',
        'initial deal', 'invalid single and batch', 'draw and recover',
        'execution plans', 'skill executor', 'program gameplay hashes',
        'skill execution reads hand context', 'ordinary trick queries preserve exact options',
        'legal action queries preserve exact physical entity options', 'invariant history index',
        'physical deck recipes', 'structured skill metadata', 'content registry',
        'standard package', 'composition kernel', 'rule query', 'slash resolution',
        'dying response', 'Xingshang', 'response use completion', 'selected gift',
        'configured active sequences', 'standard active programs', 'owned-card set',
        'turn card-use effects', 'active Program contracts', 'hand guidance',
        'actual marker payment', 'replacement draw and dying payment', 'two dynamic actual ends',
        'ordered nested native owner', 'payment nested comparison', 'first target history',
        'program conversion polarity shared state and replay',
        'Feng Lin Lu Zhi actual discard entry boundaries',
        'Ending child gift joins current boundary',
        'Feng Lin Yuan Shu command loss regrant source suppression',
        'Feng Lin Yuan Shu qualified awakening persistent local loss',
        'Feng Lin Zhou Fei first domains and true equipment sequence',
        'Feng Lin Zhou Fei same-source association freeze',
        'Feng Lin Congjian Equipment gift nested replay',
        'after turn ended return movement prelude ordering',
        'after turn ended due before window nested replay',
        'Feng Lin Zuo Ci initial privacy and replay',
        'Feng Lin Zuo Ci layered suppression and local disable',
        'Feng Lin Zuo Ci same avatar program and actual end',
        'Feng Lin Yu Ji',
        'boundary Lu Meng all table printed suits replay',
        'boundary Lu Meng cross owner skip chain resume death',
        'boundary Lu Meng Qinxue windows shared usage',
        'boundary Lu Meng opt in usage legacy shape',
        'Boundary Huang Gai actual provider color',
        'Boundary Huang Gai multi card color source lifecycle',
        'boundary Lu Xun actual trick hold lianying and return',
        'boundary Lu Xun HE payment exact Hand batch count',
        'boundary Liu Bei virtual Peach HP child',
        'boundary Liu Bei native provided use decline once',
        'boundary Liu Bei gift threshold recipient',
        'boundary Da Qiao atomic mixed discard replay',
        'boundary Hua Tuo ordered actual discard effective suit receipts',
        'participant discard mandatory cost cancellation preserves legal composition',
        'current turn nonlocked suppression host lifecycle audit',
        'boundary Guan Yu actual Played and black Hand rejection',
        'Boundary Zhang Fei actual recovery receipt limited child',
        'boundary Ma Chao Tieqi Paoxiao exact cancellation integration',
        'boundary Xiahou Dun real phases skip quota expiry',
        'boundary Xiahou Dun receipt before gain child source audit',
        'Exact top count partition normal draw',
        'Bound draw receipt per point nested gain',
        'boundary Zhen Ji exact receipt stop red discard',
        'boundary Zhen Ji receipt before child source loss',
        'Unconverted Trick draw receipt disposition',
        'Foreign equipment discard program selections',
        'Population reorder actual partition and short pile',
        'Population reorder real Ending Extra Scheduled',
        'HP pair freezes after payment children before draw children',
        'Equipment placement slot self equal boundaries',
        'Final target Slash frozen comparisons actual paid Dodge',
        'Final target Slash escalation:',
        'Paid HP loss rescue and gain children',
        'Paid HP loss source and legacy',
        'Boundary Deng Ai own turn slash discard judges authority',
        'Boundary Deng Ai awakening grants snatch and extra turn',
        'Boundary Jiang Wei declined taunt discards target card',
        'Boundary Jiang Wei dodged slash still discards',
        'Boundary Jiang Wei taunt runs twice per phase',
        'Boundary Jiang Wei awakening wakes once across phases',
        'Boundary Sun Ce own duel and red slash draw',
        'Boundary Sun Ce reclaim once per turn',
        'Boundary Sun Ce hunzi wakes draws and stays silent',
        'Boundary Sun Ce zhiba declined claim discards both'
        'Boundary Zhu Rong juxiang immunity claims resolved barbarian',
        'Boundary Zhu Rong winning pindian takes target card',
        'Boundary Zhu Rong lost pindian takes nothing',
        'Boundary Zhu Rong unlimited slash damage draws at phase end',
        'Boundary Zhu Rong dodged slash skips phase end draw',
        'Boundary Zhu Rong changbiao runs once per phase',
        'Boundary Meng Huo definitions and metadata',
        'Boundary Meng Huo barbarian immunity and attribution',
        'Boundary Meng Huo zaiqi asks chosen participants in order',
        'Boundary Meng Huo zaiqi draw only at full owner',
        'Boundary Meng Huo zaiqi decline leaves everyone alone',
        'Boundary Meng Huo zaiqi stays silent without red discards',,
        'Boundary Guan Xing Zhang Bao converted slash response follows pair color',
        'Boundary Guan Xing Zhang Bao turn skills expire with the turn'
        'Damage target mount paid children source lifetime',
        'Damage appearance Draw definitions physical colors cardless legacy',
        'Selected actor Duel actual Use and Nullification',
        'Damage target obtain nested Duel native cold',
        'Boundary Yuan Shao population start role marker limit',
        'Boundary Yuan Shao conversion actual remaining targets'
        'Recovery replacement Silver Lion Zhiheng HP and reward children',
        'Recovery replacement paid equipment tail',
        'Recovery replacement faction request Silver Lion cost before providers',
        'Program Iron Chain third target owned recast',
        'Equipment recast Silver Lion recovery and movement children',
        'BoundaryXuShu fixed target real Slash',
        'BoundaryXuShu declared deck criterion'
        'Character turned over Shebian both directions',
        'Character turned over Shebian occupied equipment slot',
        'Character turned over actual damage cursor',
        'Capped hand refresh',
        'HP paid shield',
        'Random Pindian',
        'Maximum Slash Pindian',
        'Bound card recast dynamic Slash',
        'Bound card recast Silver Lion',
        'Turn kind hand exemption',
        'Signed Slash modifier',
        'Bound discard Slash frozen suit',
        'Bound discard Slash equipment',
        'First round limited refund exact',
        'Current Slash entity claim basic',
        'Current Slash entity claim nonbasic',
        'Participant hand declined private take',
        'Participant hand mixed HE gift',
        'Participant hand per point effective red',
        'Participant hand program bound alcohol',
        'Next-use rank bonus',
        'Other dying recovery equipment',
        'Alternative phase cost actual',
        'Alternative phase cost equipped',
        'Ending hand count history',
        'Random reveal color Fire Attack',
        'Unrespondable counterspell equipment',
        'Discarded provenance virtual Alcohol',
        'Discarded provenance exact discard judgment',
        'Discarded provenance real turn all materials',
        'Actual turn use kinds independent hand suits',
        'Actual turn use kinds per Play draw',
        'Owner batch loss equipment OR two cards once',
        'Shared Slash gift equipment recovery both gain children cold'
        'Turn damage-use draw debt actual gain and frozen ending cost'
        'Source faction prevention quota opaque HEJ equipment children'
    )
    Wpf = @(
        'identity general choices', 'general selection switches related',
        'chained state basic UI:',
        'Last zone conversion presentation:',
        'Original hand tag presentation:',
        'Draw-funded zero Use',
        'original card artwork', 'overlapping hand', 'composed skills', 'conversion choices',
        'response context', 'hand responses', 'opaque target-card',
        'skill target selection',
        'battle feedback', 'card flights', 'public card table',
        'playback batches', 'saved UI boundaries', 'failed writes', 'public markers',
        'deferred hand alignment', 'Program conversion polarity stays visible',
        'declaration and general library views protect private faces',
        'Jin faction presentation:',
        'Program paid choices',
        'Program exact top count restores private shared order',
        'Program population count private faces restore shared free order'
        'Program Iron Chain guide follows actual target count'
    )
}
